### ISSUE TITLE
Could not load service recipe

### ISSUE THREAD

**Issue by JaumeRF** [ferdium/ferdium-app#1025]
### Avoid duplicates

- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

macOS

### Operating System Version

macOS Ventura 13.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I just want to have the services as usual, but for some reason, they have disappeared. 

I have tried adding new services but it doesn't work.

### Actual Behavior

The services I used to use have disappeared. And when I try to add a new service, it says that the service recipe could not be loaded. 

I have tried to add services with Ferdium picks, with Custom Websites and with Custom Services and they all give me the same error.

### Steps to reproduce

1. Open Ferdium
2. Try adding a new service
3. Error

### Screenshots

<img width="1134" alt="Captura de pantalla 2023-02-26 a las 12 34 01" src="https://user-images.githubusercontent.com/37417159/221408459-f8b61f85-48e4-4d68-9837-b65752580f55.png">

**Comment by metaproph3t** [comment]
I am getting the same error on Linux Debian x86 (networking over Tor, if that matters). Everything was working fine for ~1 month, but now this error pops up whenever I try to add a new service.

**Comment by JaumeRF** [comment]
I fixed it by erasing all my workspaces. I don't know why, but for some reason when I have more than 1 workspace this error appears.

**Comment by vraravam** [comment]
@JaumeRF - do you use Ferdium with a server where your config is backed up? Or do you use the accountless option?
(With the latter, ferdium runs an internal server locally so that the interfaces and behavior are exactly the same when compared to the remote hosted server).

The reason for my question is that the most likely reason for this "no services found" scenario is when the remote server is not accessible or somehow corrupts the configuration.

**Comment by JaumeRF** [comment]
I use Ferdium with the accountless option. 

I already solved the problem just by deleting the workspaces. I donk think it had anything to do with the remote server.

**Comment by cosmicaug** [comment]
Running Linux Mint 21.1 x86_64 Cinnamon edition.

I'm having this issue. I have been using it for months as a Whatsapp client. Recently I tried to add other services (Twitter & Mastodon). At one point I tried adding Buffer and it gave me the message shown in the OP: "Could not load service recipe".

Now it has become unusable. It starts with a blank screen.
![image](https://github.com/ferdium/ferdium-app/assets/20343618/99ce9c60-56be-41cf-9920-bfbd5cc15113)

This seems to be because it seems that it cannot load **_any_** of the services (if I try, I get that "Could not load service recipe" message).

My fix was to do a reinstall. It was a Flatpak install. I used the software manager to uninstall & re-install but that was not enough. I tried again making sure to remove the files at `~/.var/app/org.ferdium.Ferdium` and that worked. Nevertheless, I would like to know what broke this in the first place as having to randomly re-install this application is not optimal.

ETA: I added system information & the fix that worked for me.

**Comment by cosmicaug** [comment]
As a followup, the culprit seems to be the Buffer service. When adding this service, the "Could not load service recipe" error will happen. When restarting Ferdium after this, other services will also be unable to load.

Also, I never used workspaces.

**Comment by iamnolanhu** [comment]
> As a followup, the culprit seems to be the Buffer service. When adding this service, the "Could not load service recipe" error will happen. When restarting Ferdium after this, other services will also be unable to load.
> 
> Also, I never used workspaces.

I got this issue when adding the buffer service as well. Now I can't add any other service no matter how many restarts or reinstalls I do.

**Comment by chrissy-dev** [comment]
> > As a followup, the culprit seems to be the Buffer service. When adding this service, the "Could not load service recipe" error will happen. When restarting Ferdium after this, other services will also be unable to load.
> > Also, I never used workspaces.
> 
> I got this issue when adding the buffer service as well. Now I can't add any other service no matter how many restarts or reinstalls I do.

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/3ca3a9f8-df5e-4cc0-88f5-f2ab367e83d1" />

I know this is old, but sharing in case anyone else run it's the issue. Open your `Profile` folder via settings > advanced settings within Ferdium. Go into `/recipies` and delete the buffer folder. Restart Ferdium.
