### ISSUE TITLE
Windows 7 issue with Kernel32.dll with latest release

### ISSUE THREAD

**Issue by Virgus** [ferdium/ferdium-app#1075]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6-nightly.9

### What Operating System are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.4-nightly.1

### Expected Behavior

Hello, I updated my Ferdium to the latest nightly release, it's working fine on my W10 setup but not on my everyday W7 partition. I had to move back to the previous nightly release.

Is it an electron issue ? Or is it related to the APPX stuff packages of W10 that's missing on W7 ? Is there a way to keep backwards compatibility with W7 that's still a great OS for everyday use ?
Thanks, V.

### Actual Behavior

The error says; "Entry Point Not Found"
The procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll

### Steps to reproduce

Just open latest nightly build on a W7 OS.

### Screenshots

![Screenshot 20230324_102106](https://user-images.githubusercontent.com/6388217/227481893-2e195295-ec27-4c92-bb9e-2fd64defec45.png)

**Comment by Alphrag** [comment]
Hi @Virgus, if you really have made the jump from 6.2.4-nightly.1 and 6.2.6-nightly.9 it is a very big gap and the problem is likely coming from [electron dropping support for W7 from version 23](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice). This means in particular that the last version we have that will work with W7 is 6.2.5-nightly.1 as we upgraded to electron.23 in 6.2.5-nightly.3.

Unfortunately, we can't go back to earlier updates from electron because of some security issues, and the fact that support for 22.x will be dropped in two months. Of course, you are free to fork this project to keep as many incoming changes as possible while locking your version to electron 22, but we don't have the resources to maintain that ourselves.

I am closing this ticket since this answer the query, but if you have any questions (such as setting your own environment in gh to build your fork) feel free to ask.
