### ISSUE TITLE
Can I change default font of all my services in Ferdium?

### ISSUE THREAD

**Issue by cg00001** [ferdium/ferdium-app#1129]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

I searched and it seems there is no way I can change fonts in services, using Arch Linux.

### Proposed Solution

A way to change default fonts.

### Alternatives Considered

I don't mind if it's a complicated solution involving Electron, etc.

**Comment by marie-bnl** [comment]
That would involve going against the websites’ choice for fonts, which could make it look terrible and breaks things.

But the only solution I see at the moment is putting something like this in the `user.css` of every service (if you don’t want to do it manually just make a little Python or bash script which does it for you).

```css
* {
  font-family: "your font" !important;
}
```

I think having to put it in every `user.css` isn’t necessarily a bad thing, because chances are you’ll need to make per-service fixes for it to look good.

**Comment by cg00001** [comment]
> ```css
> * {
>   font-family: "your font" !important;
> }
> ```

Thank you, exactly what I needed.
