### ISSUE TITLE
Feature: Add support for cloud music players like Spotify, Deezer, SoundCloud

### ISSUE THREAD

**Issue by MurzNN** [ferdium/ferdium-app#113]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There were several apps that can aggregate cloud music providers and provide a unified interface for control music playing status in all of them:

- https://gitlab.com/ColinDuquesnoy/MellowPlayer
- https://nuvola.tiliado.eu/
- https://getharmony.xyz/
- https://www.pimusicbox.com/
- https://tizonia.org/

But last years development of all of them is stopped or paused, so now world seems doesn't have any such application to listen music from several cloud providers with unified interface.

### Proposed Solution

Ferdium already has a great UI to manage multiple web services, flexible recipes API, workflow to install and configure services, settings syncs and many other parts, that suit for managing cloud music providers too! 

To add minimal support for cloud music providers to Ferdium seems we don't need so much: all that we need at minimum - is to add "Play / Pause / Stop / Next / Previous" bundle of buttons to somewhere interface (with binding to global keyboard shortcuts), and pass those events to selected cloud provider. And via next unhurried steps - add displaying now playing song title, scrubbling to Last.fm, etc.

So maybe we can consider that extending of Ferdium to cloud music players word? Or maybe start a separate project like Ferdium-Music with such functionality, with reusing and sharing most of the Ferdium code and infrastructure parts?

What do you think about this idea?

### Alternatives Considered

Alternatively we can start a new separate project from the scratch, but reusing Ferdi as base for such music player, I think, makes the first steps much easier!

**Comment by vraravam** [comment]
Ferdium basically renders the websites of the services that are configured. I don't think extending this to playing music is anywhere close to what Ferdium can do. There's also the question of DRM - which electron does not support. Closing this ticket since its way out of what we can accomplish in Ferdium/Electron. Nice suggestion though.

**Comment by ThinkSalat** [comment]
![image](https://user-images.githubusercontent.com/31082405/217003281-66d7bdac-3e70-4546-870e-4ca2210b0972.png)
Here I am running a literal video on plex with sound and everything. 

Here is rambox, another electron app, running spotify

![image](https://user-images.githubusercontent.com/31082405/217004185-f981adc4-12ab-4eeb-a280-c6d2c9155f58.png)

> Ferdium basically renders the websites of the services that are configured. I don't think extending this to playing music is anywhere close to what Ferdium can do. There's also the question of DRM - which electron does not support. Closing this ticket since its way out of what we can accomplish in Ferdium/Electron. Nice suggestion though.

This is just demonstrably wrong and you should unclose this issue so that it can be worked on. Not that the spotify web player is anything but trash compared to native, but it's better than nothing and the people who want to use it should be able to. I'm thinking it's almost certainly just a change in user agent or other one liner to get spotify working.

**Comment by SpecialAro** [comment]
Hello!

Maybe this https://github.com/ferdium/ferdium-app/pull/720 can unlock adding Spotify as a service in Ferdium, for instance. @vraravam will you agree on re-opening this issue?

Nevertheless, I'm linking this issue so users can track the status (which is related to this implementation): https://github.com/ferdium/ferdium-app/issues/687

**Comment by vraravam** [comment]
I dont think we should use binaries that are not from the original source: https://github.com/ferdium/ferdium-app/pull/720#issuecomment-1296361687.

I think its not only me, but all the other contributors who need to vote. If we go ahead, I dont know what kind of security vulnerabiities might be introduced (we dont know the supply chain for the external binaries)

**Comment by SpecialAro** [comment]
I agree with you security wise... that's why I'm also reluctant to merge that PR as is.

Nevertheless, as per @kris7t comment (https://github.com/ferdium/ferdium-app/pull/720#issuecomment-1296464355) it seems like it is possible to implement some logic that extracts the CDM from the official chrome installer (also with a toggle setting on Ferdium to enable this feature). Or, like @bchen290 told we can have settings where the user can set the Widevine library path and version.

I really don't know if we should try this or not (and I also lack knowledge to do it myself), so let's see what the other devs think about this aswell

**Comment by ThinkSalat** [comment]
Great spotting @SpecialAro! Why not throw together 
[this](https://github.com/ferdium/ferdium-app/pull/720#issuecomment-1296464355)  as a kludgy prototype and let some of the users who have been asking for the feature test it out. I think it's quite close to the best of all worlds. Blessed by Google be damned.

**Comment by gitunixbyte** [comment]
Any updates on this?
