### ISSUE TITLE
Cant login to google classroom, opening another browser instead of loging in

### ISSUE THREAD

**Issue by Yugsolanki** [ferdium/ferdium-app#1135]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.2.6

### Recipe Name

Google Classroom

### Recipe Version

1.2.1

### Steps to reproduce

1. Add Google Classroom as a service
2. Click on google classroom
3. Then click on Sign In button on the top right corner
4. Click on Google Classroom
5. as soon you click on google classroom, it is suppose to give you sign with google option but i open a new tab in another browser (brave in my case) i want to sign in but cant.

### Expected Behavior

I am suppose to sign in to google classroom, and not be redirected to a different browser

### Actual Behavior

it open another browser (brave in my case) and show me google classroom there which offcourse i dont want.

### Screenshots

![image](https://user-images.githubusercontent.com/65902617/234885076-9575781b-4cbc-43a0-9301-5bb48ba1ce1f.png)
![image](https://user-images.githubusercontent.com/65902617/234885097-322a38ac-5761-4b9f-b731-f7b8c08c4197.png)

**Comment by marie-bnl** [comment]
It seems like the issue is the “Google Classroom” link here has `target="_blank"`. It normally tells the browser to open the link in a new tab, but Ferdium can’t so it opens it in another browser.

Here are some solutions that could work but feel like dirty workarounds:

1. Remove that `target` attribute from the service’s `webview.js`, which works well but implies making useless checks each time but the first one (to check whether the current URL is that of “Google for Education“ home page and remove the target if it is), which is a little waste of performance, though not that terrible.
2. Using as URL : https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fclassroom.google.com instead of https://classroom.google.com/u/0/. This is the href of the “Google Classroom” link above. It makes it work for non logged-in users, but implies that logged-in users always land on the log-in page, where they are immediatly redirected to Classroom (instead of just landing on Classroom directly). This makes it even slower for logged-in users so I’d rule out this option in favour of the first one.

**Comment by marie-bnl** [comment]
This is the same issue as #1064.

**Comment by Yugsolanki** [comment]
> It seems like the issue is the “Google Classroom” link here has `target="_blank"`. It normally tells the browser to open the link in a new tab, but Ferdium can’t so it opens it in another browser.
> 
> Here are some solutions that could work but feel like dirty workarounds:
> 
>     1. Remove that `target` attribute from the service’s `webview.js`, which works well but implies making useless checks each time but the first one (to check whether the current URL is that of “Google for Education“ home page and remove the target if it is), which is a little waste of performance, though not that terrible.
> 
>     2. Using as URL : https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fclassroom.google.com instead of https://classroom.google.com/u/0/. This is the href of the “Google Classroom” link above. It makes it work for non logged-in users, but implies that logged-in users always land on the log-in page, where they are immediatly redirected to Classroom (instead of just landing on Classroom directly). This makes it even slower for logged-in users so I’d rule out this option in favour of the first one.

Thank you so much
