### ISSUE TITLE
Entry point not found 

### ISSUE THREAD

**Issue by okthatsactuallyme** [ferdium/ferdium-app#1170]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.7.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 8.1

### What arch are you using?

x64

### Expected Behavior

I had installed the app long ago but only decided to use it today. After about 3-4 hrs of working with the app and everything running smoothly and as expected, I get a notification saying the app can be updated so I clicked on it. 

### Actual Behavior

Instead of the app getting updated and opening, I faced an error saying entry point not found.

### Steps to reproduce

1. Click on install update
2. The installation will fail and face an error

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/73371160/32193601-3800-45e6-b5ba-faf3f8366050)

**Comment by vraravam** [comment]
As notified [here](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice), electron (the base framework upon which Ferdium is built) no longer supports windows 8.1

This means in particular that the last version we have that will work with W8.1 is 6.2.5-nightly.1.

Unfortunately, we can't go back to earlier updates from electron because of some security issues, and the fact that support for 22.x will be dropped in two months. Of course, you are free to fork this project to keep as many incoming changes as possible while locking your version to electron 22, but we don't have the resources to maintain that ourselves.

I am closing this ticket since this answer the query, but if you have any questions (such as setting your own environment in gh to build your fork) feel free to ask.
