### ISSUE TITLE
flatpak outdated - currently 6.2.6 should be 6.2.7

### ISSUE THREAD

**Issue by matthewdavis** [ferdium/ferdium-app#1206]
### Your issue

As $TITLE says, flathub has not been updated with latest version.

**Comment by Alphrag** [comment]
This is strange since the flatpack repository was updated accordingly (cf https://github.com/flathub/org.ferdium.Ferdium/commit/cf8c1e66084651197e56deb42eecd23f5788b308 ). If this has not been propagated, please raise an issue directly to flathub.

Also in the future, please use the templates provided to create issues, this helps us a lot.
