### ISSUE TITLE
MacOS - Navigation bar buttons partially obscured by invisible window title bar

### ISSUE THREAD

**Issue by nexxai** [ferdium/ferdium-app#1221]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.2.7

### Recipe Name

Twitter

### Recipe Version

1.3.0

### Steps to reproduce

1. Open any tweet
2. Click on any other Twitter-hosted link listed on that screen
3. Attempt to use the back arrow button at the top-left corner of the page

### Expected Behavior

The entire back arrow button to be clickable.

### Actual Behavior

Notice that while hovering over any part of the arrow button changes the button to its hover state, the top half of the circular arrow button is actually unclickable; the bottom half of the button can be clicked

I assume (but cannot prove) that this is due to Ferdium not having a title bar and macOS expecting there to be one there.  The dimensions of what is being blocked vs. what is not seem to approximately fit this hypothesis.

**Comment by Alphrag** [comment]
Hi @nexxai, thanks for logging this. In fact, this is not a bug, but it is a feature and is independent of any recipe. Indeed, having a useless title bar seemed a lack of space for us, but it is necessary to have such a zone in order to allow the window to be dragged around. We decided to have a few pixels which are displaying something that cannot be interacted with (as it is superseded by the draggable area) to gain this in height of the content.

If you don't like this behaviour, you can go to `Settings -> Appearance -> Show draggable area on window` which will show the title bar, pushing all the content a few pixels lower, and then the buttons are fully clickable.

**Comment by nexxai** [comment]
Dammit! The minimalist in me is furious and the developer in me completely understands. :) 

Thanks for responding so quickly.
