### ISSUE TITLE
Cannot switch from telegram A version to K version using telegram menu

### ISSUE THREAD

**Issue by MadelineProtoFan** [ferdium/ferdium-app#1245]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.3.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When i press to switch telegram from A version to K verison - telegram is opening in normal browser (not in ferdium)

### Actual Behavior

When i press to switch telegram from A version to K verison - telegram is opening in normal browser (not in ferdium)

### Steps to reproduce

Go to telegram in ferdium
Try to swtich A version to K version in telegram menu

**Comment by Alphrag** [comment]
Hi, this is because the telegram service blocks all urls to verify them before opening them accordingly (in Ferdium or in the browser) which is not fully working as it should. However, you can switch to the other version by either right-clicking on the switch in the telegram interface to chose "Open in Ferdium", or in the setting of your telegram service select "Open URLs within Ferdium" which will force them to open most links on the app instead of your current browser.

Interestingly enough, switching from the `K` version to the `A` one does not suffer the same drawback because of the different implementation that completely bypasses our tests.

**Comment by MadelineProtoFan** [comment]
Ok thanks for the info
