### ISSUE TITLE
No console log (debugging possible) > node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error 

### ISSUE THREAD

**Issue by hirschferkel** [ferdium/ferdium-app#1337]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1

### What Operating System are you using?

macOS

### Operating System Version

Monterey

### What arch are you using?

x64

### Last Known Working Ferdium version

6.4.1 - OS X

### Expected Behavior

Console Log "Hello, World!"

### Actual Behavior

node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error 

Uncaught (in promise) Error: Error invoking remote method 'get-dnd': Error: ENOTDIR: not a directory, stat '/Applications/Ferdium.app/Contents/Resources/app.asar/electron/ipc-api/node_modules/macos-notification-state'
    at a.invoke (node:electron/js2c/renderer_init:2:7723)
    at async i._systemDND (/Applications/Ferdium.app/Contents/Resources/app.asar/stores/AppStore.js:1:11797)
a.invoke @ node:electron/js2c/renderer_init:2
await in a.invoke (async)
(anonymous) @ /Applications/Ferdium.app/Contents/Resources/app.asar/stores/AppStore.js:1

### Steps to reproduce

Open Console (Developer Tools)

### Debug link

https://debug.ferdium.org/df82e875-5d80-4d01-bab7-f270f8733723

**Comment by SpecialAro** [comment]
Hello @hirschferkel

Thank you for logging this issue.

Can you provide more information on what your are trying to do and what are you getting?

Also, look on the code for how we use "debug" and try that, please.

**Comment by hirschferkel** [comment]
@SpecialAro  I just want to change the standard page when opening an app with user.js 

So to get see why my code does not work, I open > Open Console (Developer Tools), as I wrote, and while I activated the console.log in user.js, it will not be prompted.
That's it. There is no log in console.

But I get more and more of these errors in the console log while just having opened the page (node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error)

And much more ...
![Bildschirmfoto 2023-09-01 um 12 23 31](https://github.com/ferdium/ferdium-app/assets/16016422/75422f4e-a71a-4fab-8020-1e6dc07dcc1b)
![Bildschirmfoto 2023-09-01 um 12 23 39](https://github.com/ferdium/ferdium-app/assets/16016422/5305dd71-4f6c-4a89-a45a-9ec974390ead)

**Comment by SpecialAro** [comment]
Hey! Been meaning to comment on the other issue about that approach.

If you need to change the page shown by default you can easily do one of two approaches:
- create a new custom website service and add the logic there
- in the same folder of user.js just change the URL on the file package.json (bear in mind that you will need to do this every time the recipe is updated on our side - as our updates will overwrite that file)

The fact that you are not seeing the console.log is because you are probably not on the correct dev tools - you are probably looking at the dev console of Ferdium and not the WebView (that's what you want). For that got to view and press Open Service Dev Console (or something like that)

A new window should open and you should see the console.log there

**Comment by hirschferkel** [comment]
o.k. now it worked. But the messages and errors keep trashing the console log ...
<img width="910" alt="Bildschirmfoto 2023-09-02 um 08 43 32" src="https://github.com/ferdium/ferdium-app/assets/16016422/78e46712-8bad-4a35-bd1f-15eeeff5e564">

**Comment by SpecialAro** [comment]
Yes. Those errors (in reality just one) are present and it's a ongoing process to solve - it was caused when we updated mobx dependency and from JavaScript to Typescript. They can be ignored for now.

Given that the motive of this issue is fixed, I'm closing it. Feel free to comment below if you still think it should remain open.
