### ISSUE TITLE
Contributor count discrepancies

### ISSUE THREAD

**Issue by meiphoo7-Mae** [ferdium/ferdium-app#1345]
### Your issue

[This page](https://github.com/ferdium/ferdium-app) shows in the column on the righthand side 10 avatars, apparently representing the most active contributors. Additionally it says below those avatars ' +135 contributors '. So that adds up to 145 contributors. Above the avatars it shows **Contributors _146_**. So something is a little off.

Furthermore the [README.md](https://github.com/ferdium/ferdium-app/blob/develop/README.md) page shows a total of 314 avatars of contributors (if I've counted correctly) . That's a lot more than the 145 or 146 the page mentioned above states. Also this README.md page isn't updated since Jun 1, 2023 so apparently there are even more contributors than 314.

**Comment by SpecialAro** [comment]
@meiphoo7-Mae I'm closing this issue because this is working properly. The count on the righthand side is for contributors of the Ferdi/Ferdium fork of Franz - this is calculated based on the PRs and Commits of each user (if I'm not wrong) and it's not controlled by us - it is controlled by Github.

Also, the README shows all the contributors that have contributed to not only Ferdium but also Ferdi and Franz (given that we are a fork of a fork). This also is updated automatically by using the allcontributors bot.

**Comment by meiphoo7-Mae** [comment]
It was not exactly meant to be an issue but just an observation. Thanks for confirming that this is functioning properly.
