### ISSUE TITLE
Issue: High disk load

### ISSUE THREAD

**Issue by sufehmi** [ferdium/ferdium-app#1413]
### Your issue

Hi, does anyone notices that Ferdium accesses the storage, a lot? 
I'm concerned that this may cause premature failure for the disk.

In Linux, I worked around this by moving Ferdium's folder to SSD, then symlink-ed it to the folder in the HDD where it expect it.

Now in Mac, I noticed that Ferdium still accesses the storage a lot / very often.
I shouldn't be surprised and should expect the same behaviour in all of its platforms, but anyway.

Any ideas? 

Or perhaps should I create a launcher ; which will create a RAM disk, copy Ferdium's folder there - then run Ferdium , and automatically (r)sync the contents in ramdisk to its real folder in constant interval, and (r)sync again once Ferdium is closed?

Thanks.

**Comment by SpecialAro** [comment]
Hello @sufehmi

Which Ferdium version and OS are you using? You should have opened this issue with the corresponding template.

Do you use Ferdium with or without an account?

How much/which services are you using?

**Comment by sufehmi** [comment]
> Hello @sufehmi
> 
> Which Ferdium version and OS are you using? 

Hi, thanks, it's version 6.5.2 on MacOS

> You should have opened this issue with the corresponding template.

Apologies, I wasn't sure which template was the right one for this.

> Do you use Ferdium with or without an account?

No account.


> How much/which services are you using?

3 x WhatsApp accounts, 1 x Discord, and 1 x Slack

Thanks again.

**Comment by vraravam** [comment]
Ferdium is built on top of Electron, which in turn embeds Chromium tabs. What you are describing is not something we can control. This is a pure upstream dependency.

**Comment by mjeveritt** [comment]
Whilst I respect this is a classic case of RESO:WONT (in Bugzilla parlance) .. is there really Nothing that can be done downstream?
I also respect that Electron is a 'black-box' solution to the idea of embedding web-clients of chat messengers, but when you reach the point of running 8+ services and each is storing some silly GB of "data" (Cache or whatever) in your profile directory, surely you can see this isn't sustainable?!
I note https://github.com/ferdium/ferdium-app/issues/916 as a partial solution to this problem, but how would we go about implementing this, both on the Ferdium core level, and on the service/recipe level?
I'm sure if we started looking at the framework in the App, we could start testing individual services and seeing what 'broke' in order to refine the necessary code?!
I'm already experiencing some 'unhelpful' behaviour from a secondary WhatsApp account I use, and one or two other 'rogue' services which don't cache their login/session data properly, so this could possibly address that issue as well (separate issue, not-filed yet!)
(and I'm not even starting here on the weirdness that is Meta/"business-suite" which is broken at the moment too!)

**Comment by sufehmi** [comment]
Hi @mjeveritt , thanks for raising this issue again.

Currently I'm mitigating this by running my 3 WhatsApp accounts on Firefox - using the Multi-Account  Containers addon = https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

Now I'm seeing much much lower I/O activities on the disk

This should help on prolonging the disk's usability 

Hope it helps anyone on the similar situation.
