### ISSUE TITLE
Navigation bar fails to hide

### ISSUE THREAD

**Issue by steveharsant** [ferdium/ferdium-app#1474]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.6.0

### What Operating System are you using?

macOS

### Operating System Version

Sonoma 14.1.2 (23B92)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

N/A

### Expected Behavior

When changing Settings > Services > Navigation Bar Behaviour to 'Never show navigation bar', the navigation bar (with forward/back buttons & URL) should hide for all services.

### Actual Behavior

The navigation bar never hides for any services.

### Steps to reproduce

1. Set Settings > Services > Navigation Bar Behaviour to 'Never show navigation bar'
2. Observe visible navigation bar.

### Debug link

https://debug.ferdium.org/6efc25ae-fa2f-4a31-9bfa-a9bfc44b64d7

### Screenshots

![ferdium bug](https://github.com/ferdium/ferdium-app/assets/38461965/a2d16696-0063-4967-8945-86e2b0f0b988)

**Comment by privatecoder** [comment]
Press `cmd` + `B` – it will hide the Navbar. Not sure what the above setting does really.

**Comment by steveharsant** [comment]
That does the trick, thank you @Privatecoder

**Comment by RJVB** [comment]
FWIW, I like that it shows even on non-custom recipe (and wished there were no other issues with it...)

**Comment by mcmxcdev** [comment]
The problem is the following:

There are two ways to control the navigation bar in Ferdium, through "Toggle Navigation Bar", but also "Navigation bar behaviour" inside settings. Looking at the code, whenever "Toggle Navigation Bar" is active, that has precedence over any of the "Navigation bar behaviour" settings so they are completely ignored.

![image](https://github.com/ferdium/ferdium-app/assets/16797721/dee520e2-b290-41c7-bc22-7e600f0a2181)


I would say that wasn't exactly designed in a smart way since both these configurations can collide, but it all works as expected.
