### ISSUE TITLE
Bug: Ferdium overwrites settings from Ferdi

### ISSUE THREAD

**Issue by MagicLegend** [ferdium/ferdium-app#156]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.37

### What Operating System are you using?

Ubuntu

### Operating System Version

Linux <name> 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Ferdium uses a separate config folder from Ferdi.

### Actual Behavior

Adding new services in Ferdium overwrote the config for Ferdi as well.

### Steps to reproduce

1. Use Ferdi
2. Add services
3. Install Ferdium
4. Add service
5. Check Ferdi, the same services will be set up there now - and pre-existing logged in services will be gone

### Additional information

I guess it's not a major issue, but it's not how it's supposed to be. I expect Ferdium to run on it's own, not interacting with files that belong to different applications. Note that this is _not_ a duplicate of #4, because according to that issue the config should be separate. Also note that there were no services configured upon first start of Ferdium, so I'm assuming it is not reading the Ferdi config.

**Comment by SpecialAro** [comment]
Hello @MagicLegend , thank you for raising this issue.

Can you provide some more information about this?

Are you using account or accountless mode? If account mode, which Server are you using (Ferdium, Ferdi or Franz) ?

**Comment by MagicLegend** [comment]
Of course - I run both of them in accountless mode. If needed I can try to comb out the private information in both config folders and supply them to you.

**Comment by vraravam** [comment]
My suspicion is that since the Ferdi (in accountless mode) starts the internal server on a port, when Ferdium starts (also in accountless mode) it locks to the same port and ends up using the Ferdi's internal server. This might cause overwrite of the internal-server-side data. @MagicLegend - please confirm if the `<FerdiumProfile>/config/settings.json` is the one you are talking about or the sqlite db

There's also the `<FerdiumProfile>/Preferences` file - but, i think that's managed by Electron, not Ferdium directly - but, that again should follow the same semantics of the `<FerdiumProfile>/config/setting.json` ie these 2 files should be independent of Ferdi's installed location per se

**Comment by MagicLegend** [comment]
Gotcha, yes, that 110% is the issue, since Ferdi was started when I launched Ferdium for the first time. I guess Ferdium does a first-start cleanup on that port then?

**Comment by vraravam** [comment]
> I guess Ferdium does a first-start cleanup on that port then?

Since Ferdium spawned off of the same codebase as a fork, the port number is the same. We hadn't really expected users of Ferdium to continue using Ferdi. You might be a really exceptional outlier. If you continue to use both, we would have to play a card to change the port number.

**Comment by MagicLegend** [comment]
Which totally makes sense. I'm surprised that the Ferdium server was able to launch, how did it not get into a bind conflict?

I have no clue of Ferdi(um)'s internals, but perhaps it should try to use the next-available port number if something is already on the initial port?

Also, the current issues with Slack make it pretty hard to continue to use Ferdium full-time until those are resolved... #158 #162 So I'm afraid I'll be switching back-and-forth between Ferdi and Ferdium for a bit :sweat_smile:

**Comment by MagicLegend** [comment]
Looking at the code real quick, I see that an abandoned project (`@adonisjs/ignitor`) is being used for the webserver - perhaps some time should be invested to swap that to something that's actively maintained.

**Comment by vraravam** [comment]
Both Ferdi and Ferdium use the logic to search for next available port number - but, they are also "intelligent" in that they not only check for port in use, but also whether it responds to a known header. thus, they both zero in on the same running server process.

Yes, upgrade of adonis is pretty high on my list - but, i am looking for some help with the actual upgrade. Since the jump is across multiple major versions, its not a drop-in with minor tweaks. I tried recreating from scratch with the latest, but since I'm not a javascript dev, I hit some ceiling.

**Comment by MagicLegend** [comment]
> Both Ferdi and Ferdium use the logic to search for next available port number - but, they are also "intelligent" in that they not only check for port in use, but also whether it responds to a known header. thus, they both zero in on the same running server process.

Hah, yeah, of course. Maybe Ferdium should look for a ferdium-unique header then? I mean, it is pretty specific - but changing the name of the header should be a find-and-replace operation?

> Yes, upgrade of adonis is pretty high on my list - but, i am looking for some help with the actual upgrade. Since the jump is across multiple major versions, its not a drop-in with minor tweaks. I tried recreating from scratch with the latest, but since I'm not a javascript dev, I hit some ceiling.

Hmm, yeah, that's the downside of using old packages. Upgrading them down the line is a nightmare. I'm not sure if I can be of much help here either, but perhaps someone else on the team feels up for the task?

Also, for a non-JS dev you do an awful lot of great work in a project that is >90% JS/TS :wink:

**Comment by vraravam** [comment]
> Hah, yeah, of course. Maybe Ferdium should look for a ferdium-unique header then?

So, I figured out that it was not using such sophistication - just a prcess running and responding on a port. I have changed the default port in the above mentioned PR. This should fix your specific problem @MagicLegend . If it gets approved in the next couple of hours, it'll show up in the next nightly.

**Comment by MagicLegend** [comment]
That's of course also a solution! Thank you! I'm gonna close the ticket then, since this should never be an issue anymore :)
