### ISSUE TITLE
Please add Notion Calender to the latest update.

### ISSUE THREAD

**Issue by yohanesanri** [ferdium/ferdium-app#1599]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+request+%3Asparkles%3A%22) for a recipe request that matches the one I want to file, without success.

### Name of the service

Notion Calendar

### URL of the service

https://calendar.notion.so/

### Features you want implemented

Notification support, integration with reminder in Notion recipes on Ferdium.

**Comment by NocturnalNick** [comment]
@SpecialAro @yohanesanri 
How do you log into Notion Calendar? The "Sign in with Google" button only opens externally (even with Ferdium told otherwise) and there's no right click option to open in internal browser. If I log in to another google service (by changing the URL in the notion calendar service) it still brings me to the login page and I have the same issue :-S
