### ISSUE TITLE
How Do I Re-Enable a Service?

### ISSUE THREAD

**Issue by monkeylove** [ferdium/ferdium-app#1684]
### Your issue

I accidentally disabled a service in Settings - General - Enable Service. It disappeared from the "your services" list. How do I re-enable it?

**Comment by SpecialAro** [comment]
Hello @monkeylove I don't see any "Enable Service" in the Settings - General tab

Are you referring to this?
![image](https://github.com/ferdium/ferdium-app/assets/37463445/0bded610-045e-4bb6-be69-f7174275d3dd)

When you disable a service it should stay as Discord shows on the list (gray). You probably deleted the service, that is why it doesn't show up on "Your Services" tab.

I'm closing this issue for now (so that we don't clog the issue board), if you have any doubts comment bellow or ping me on discord!

**Comment by monkeylove** [comment]
Thanks. I'm sure I didn't delete it. Here's what happened:

I've two Twitter accounts, so I made two Twitter services.

I went to one (I was looking to remove notifications) and decided to experiment by toggling the "enable service" setting. After that, the Twitter service disappeared. That is, it wasn't greyed out but gone, but the other Twitter service was still there.

I had to create a new Twitter service and re-login to the account.
