### ISSUE TITLE
Whatsapp and Discord (maybe others) logout after some time of no usage in Ferdium

### ISSUE THREAD

**Issue by vraravam** [ferdium/ferdium-app#17]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Steps to reproduce

1. Add Whatsapp as a service into Ferdium
2. Login after scanning the QR code
3. Do not use Whatsapp in Ferdium for some time (15+ mins?)
4. You are logged out

### Debug link

na

### Additional information

This seems to have been an after-effect of the upgrade from electron 15.3 to 16 and beyond. Might need to investigate if we have to do some special processing. We are already using the persisted sessions for all webviews, but this doesn't seem to work atm

**Comment by vraravam** [comment]
Might be related to this? https://github.com/electron/electron/issues/959#issuecomment-985964273

**Comment by SpecialAro** [comment]
I'm having a similar problem with Whatsapp whenever I close and open Ferdium. It seems that credentials are not persistent.
Tho, for messenger everything is fine.

**Comment by kris7t** [comment]
My guess would be something related to https://github.com/electron/electron/issues/31689

We should check whether there's anything in the webview preload script (https://github.com/ferdium/ferdium-app/blob/develop/src/webview/recipe.js and all the stuff it imports) that tries to access `localStorage`.

The most likely problem is the `require('debug')` call (in `recipe.js` and probably in numerous scripts it imports), because the `debug` NPM package attempts to use `localStorage` to save the current log level: https://www.npmjs.com/package/debug#user-content-browser-support Due to the electron bug above, user data in the service will be lost.

**Comment by mmajewsk** [comment]
I have the same issue in 6.7.0 and solemly occuring in whatsapp and discord

**Comment by uroybd** [comment]
This issue still persists.

**Comment by odie16** [comment]
Happening to me too with WhatsApp on version 6.7.2.

**Comment by theoratkin** [comment]
I recently (in the last 2-3 weeks) started having this problem with Discord, it logs me out on every restart. Is this a problem with Ferdium or Electron?
