### ISSUE TITLE
Segfault after update to 6.7.3

### ISSUE THREAD

**Issue by Mihara** [ferdium/ferdium-app#1721]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3-amd64

### What Operating System are you using?

Ubuntu

### Operating System Version

22.04.4

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.2-amd64

### Expected Behavior

Expected behavior is actually starting up after automatically updating to 6.7.3.

### Actual Behavior

```
$ ferdium
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Segmentation fault
```

Leaving me no avenues to explore for what is *actually* wrong.

### Steps to reproduce

Update to 6.7.3.

### Additional information

Downgrading back to 6.7.2 gets it to start up normally.

**Comment by arvchristos** [comment]
Experienced exactly the same. For me, launching `ferdium` with `electron28` instead of `electron29` did the trick but seems like a temporary fix.

**Comment by Alphrag** [comment]
Hi guys, sorry to hear that. I have been using it on Ubuntu 23.10 without any troubles, so I didn't think that it would cause problem on an earlier version of the OS. 
Maybe if you try to run the AppImage, you will get more information that could help us? What version of the linux kernel do you have?



> For me, launching `ferdium` with `electron28` instead of `electron29` did the trick but seems like a temporary fix.

@arvchristos That is weird since version `6.7.2` was already using `electron 29`, and we have updated to `electron 30` in `6.7.3`.  So what do you mean by "launching `ferdium` with `electron28`"?

**Comment by Mihara** [comment]
> Maybe if you try to run the AppImage, you will get more information that could help us?

```bash
$ ./Ferdium-linux-Portable-6.7.3-x86_64.AppImage
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: Settings@13.store
Ferdium Migration:  🧙‍  Running database migration wizard
info: serving app on http://localhost:46569
Ferdium Migration:  🔮  Migrating table from 6.7.2 to 6.7.3
```

Runs with no obvious issues at all, except logging me out of half of the services inside for some reason. There is, however, a reason I don't want to use AppImage or Flatpak with a program that keeps running continuously.

> What version of the linux kernel do you have?

```bash
# uname -r
6.6.28-x64v4-xanmod2
```
See https://xanmod.org/ though I doubt very much this is actually relevant.

**Comment by Alphrag** [comment]
> Runs with no obvious issues at all, except logging me out of half of the services inside for some reason. There is, however, a reason I don't want to use AppImage or Flatpak with a program that keeps running continuously.
 
Ok that's good to know. So it seems that it is the `.deb` update which was the problem, not the software itself. Since the autoupdate for `.deb, .rpm` and other packaging modes is still considered a beta feature in `electron-builder` that might be the cause of it. Have you tried reinstalling `6.7.3` directly from the `.deb` file on the release page? If it doesn't work, I'll try to launch a VM for testing on which nightly it started failing.
(btw, I fully understand preferring to avoid AppImage, but it can be a good indicator on where the issue lies :slightly_smiling_face: )

**Comment by Mihara** [comment]
> Have you tried reinstalling 6.7.3 directly from the .deb file on the release page?

That was the first thing I tried, still got the same segfault.

**Comment by Alphrag** [comment]
Hi @Mihara, I am sorry I can't reproduce the problem, so it is really hard to figure out where could the problem be coming from. As you can see, running Ferdium installed via the deb package under Ubuntu 22.04 LTS works perfectly fine for me:
![image](https://github.com/ferdium/ferdium-app/assets/34252790/25785f62-80a5-4ede-bc40-f5b2ce022f35)

So I don't know if this is due to some missing dependency on your end, or something different on your kernel that makes it fail, but the only way we could troubleshoot this is if you give us the first nightly for which this failed. (also trying to nuke the ferdium folder after having made a backup of it, to see if it is due to some corrupted file there)

**Comment by PauloGDPeixoto** [comment]
I have the exact same problem, I am currently using Fedora 40, but already had it with Fedora 39. I am installing the application directly from the x86_64.rpm package.
Installing the 6.7.4-nightly.4 build temporarily solved the issue, but now I started having this issue again and downgraded to 6.7.2, which still works. I started trying the other nightly builds, but the only one that worked so far was the 6.7.4-nightly.9.
While trying to figure out which versions worked or not, I ended up with a lot of icons disappearing, so for now, I'm sticking with 6.7.2.

**Comment by Mihara** [comment]
The issue no longer happens for me with 6.7.4, so unless anyone else can still reproduce it, this might need to be closed.

**Comment by Alphrag** [comment]
@PauloGDPeixoto could you please try the stable `6.7.4` release to verify if the segfault is fixed for you as well?

Regarding the icons disappearance it is because we have changed how they are handled. Now they are fetched directly online, instead of being shipped inside the app itself. Since this change was done in the `6.7.4-nightly.5` you pulled the new versions of the recipes that do not contain the icons. After that, reverting to `6.7.2` did not bring them back because the versions of the recipes included in that release were lower than the versions you had locally, and thus they were not reloaded (thus not bringing back the icons, but now missing the feature in the app to fetch them online). You would need to lower a lot the local versions of the recipes to make sure they are replaced by the one bundled in the app.

**Comment by PauloGDPeixoto** [comment]
Thanks for the clarification. I am testing 6.7.4 and so far I haven't faced the segfault.

**Comment by Alphrag** [comment]
Great, it seems like the electron updates have solved the problem then.
