### ISSUE TITLE
Is there a Ferdium version that I can run on Windows 7 64bit?

### ISSUE THREAD

**Issue by 613TheEvil** [ferdium/ferdium-app#1793]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

Latest

### What Operating System are you using?

Windows

### Operating System Version

Windows 7 Ultimate

### What arch are you using?

x64

### Last Known Working Ferdium version

Latest

### Expected Behavior

I wish I could run Ferdium on Win7.

### Actual Behavior

When I try any of the installers for Windows, Ferdium gives errors and never runs. DLL errors and crashes right after installation, so yeah...

### Steps to reproduce

Run Win 7 on an imaginary pc and go from there, I suppose. If you make it work, tell me how.

**Comment by Alphrag** [comment]
Hi @613TheEvil. Unfortunately, Ferdium is built upon electron, which (following chromium that it uses in the background) [dropped support for Windows 7/8](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice) more than a year and a half ago.
This means that the latest version of Ferdium that could run on such an OS is [version `6.2.5-nightly.1`](https://github.com/ferdium/ferdium-app/releases/tag/v6.2.5-nightly.1) (released Feb 3rd 2023). Even though this might run at the moment though some errors might be coming up, we strongly advise against it, since it does not contain any security patch added for more than a year, making you vulnerable while using it.
If you understand the issues, feel free to try it, but we won't be able to support any issues related to this.

**Comment by 613TheEvil** [comment]
Man, I am grasping at straws here, I am trying apps since morning. Anything will be fine if it works and has notifications and an unread counter working, without hoarding RAM. I don't want to be forced into looking for a new computer, even if compatibility issues keep coming up. Thanks I will try this.

**Comment by vraravam** [comment]
Closing as not planned.

**Comment by Alphrag** [comment]
> I don't want to be forced into looking for a new computer, even if compatibility issues keep coming up. 

If you are running an old computer but want it to be usable, I warmly suggest you look into moving away from windows and on to a lightweight linux distribution which would allow you to use up to date software while running fine on old hardware. 🙂 
There are many well-suited distributions available for beginners with the same feel as Windows menus if you are afraid of taking that step (to name a few: Kubuntu, Linux Lite, Linux Mint...)

**Comment by 613TheEvil** [comment]
I am not at the age that I can be bothered tinkering with linux, I did a bit at my university years, that was 2 decades ago... I would simply have other problems and compatibility issues then, nothing is perfect sadly. Eventually I will have to get some win 11 pc but yeah, not today. Thanks for the suggestion though. I will stick with Franz, the old version of Ferdium has the same behavior/problems with notifications and at least Franz can take updates, and I already set it up so, yeah. Take care kind people.

**Comment by pepper3k** [comment]
> I am not at the age that I can be bothered tinkering with linux, I did a bit at my university years, that was 2 decades ago... I would simply have other problems and compatibility issues then, nothing is perfect sadly. Eventually I will have to get some win 11 pc but yeah, not today. Thanks for the suggestion though. I will stick with Franz, the old version of Ferdium has the same behavior/problems with notifications and at least Franz can take updates, and I already set it up so, yeah. Take care kind people.

actually you could run linux mint or popos, linux desktop has come a long way and you will waste much less time getting oriented with modern versions of linux and open source software than you would dealing with the shenanigans and walled gardens of apple and microsoft.

additionally, the Wine project has come a very long way and most mainstream windows software is perfectly functional on linux using the wine compatibility layer, in some cases even having better performance on linux than on the native windows os. the suggested solution will give you more flexibility and freedom, less exposure to malware, more software options and pretty much zero cost and licensing obligations.

in case you do decide to stick with windows, make sure you take advantage of ferdium's hibernation feature, to save even more memory. for me, any app that is not and app that needs to be available for receiving calls and messages, goes into hibernation after a certain period of time. this way i can run as many services as i want without sacrificing all the required resources.

whichever path you choose, good luck. (choose linux :smile_cat: )

**Comment by 613TheEvil** [comment]
Man, my pc is more than 15 years old, I don't think it gets any upgrades, I just keep it alive as is. For a new system, yeah linux is useful for certain things, for others... It can get in the way sadly, when you have to interact with other stuff coming in from windows and android environments. Anyway, the hibernation is fine, but what I wanted is not available sadly, the notification popups. I could use Ferdium 6.2.5 instead  of Franz but, only for hibernation? I don't know...

**Comment by pepper3k** [comment]
> Man, my pc is more than 15 years old, I don't think it gets any upgrades, I just keep it alive as is. For a new system, yeah linux is useful for certain things, for others... It can get in the way sadly, when you have to interact with other stuff coming in from windows and android environments. Anyway, the hibernation is fine, but what I wanted is not available sadly, the notification popups. I could use Ferdium 6.2.5 instead of Franz but, only for hibernation? I don't know...

if you want help getting started with linux i can help you out, no problem, with hardware or software issues (you might have hardware issues that will kill performance no matter what software you run), just send me a dm

my machine is from 2012 and is running linux like a champ with all the latest software

remember, because the linux ecosystem is free and open source there are many things that are possible to do in linux (like running from ramdisk) that will give a serious boost to performance, but are not possible in windows. i look at migration to linux as a process that yields only benefits with no disadvantages.

one of the reasons that i dumped windows is because i couldn't upgrade ferdium, so maybe i can help you take the same route i took

**Comment by 613TheEvil** [comment]
I really appreciate the offer, I do. But I can't take such a monumental task on. I would risk being left without a pc for some time, I would probably need to spend a lot of time and money possibly on it, I just don't have the energy. I never doubted your words, I have had a light brush with linux as a student and I know it has potential, but, yeah... It needs you to dedicate.

**Comment by Alphrag** [comment]
>  I could use Ferdium 6.2.5 instead of Franz but, only for hibernation? I don't know...

@613TheEvil Actually, Franz is no longer actively developed and its latest version (5.10.0 released in Sep 2023) does not contain much upgrades since the one from the previous year (April 2022). So it is very unlikely that they will stay on electron 22 for a long time, if they even update the app and most of the other dependencies are quite outdated. On the other hand, Ferdium started at that time and we patched many errors, updated old dependencies, and added some other features, so it should be running better in many different ways than Franz. 

I have tried to build the current codebase of Ferdium, but with the old version of electron, and it seems to work on my Windows 10. Fortunately, there was only one small thing that needed a code change when downgrading, but I can't assure that nothing is broken. You can try to install it [from my fork](https://github.com/Alphrag/ferdium-app/releases/tag/Win7-unsafe-v6.7.5-nightly.7). Let me know if this works on your side, as the notification problem is likely fixed in our codebase.

**Comment by Alphrag** [comment]
As for linux, I fully agree with @pepper3k: long gone are the days when you needed to understand how to use a terminal to even dare touching any linux distribution! Now some are used in education in many schools exactly because they are easy and instinctive to use, while running perfectly on old computers, avoiding the schools to have to buy new ones just because they cannot upgrade to the latest Windows... I fully understand that when this is all you've known and on your only computer available, it could be a big risk to change, but then why not run it from a USB key? Yeah this seems crazy, but I actually always have a USB key (only an 8GB one) on which there is a linux that I can boot on. That way, if anything breaks on my computer, I know I can still access the basic things like internet, my emails, etc. So maybe this could be the way to try it out without fear of losing anything, or breaking your current installation of Windows 😉  
I will be happy to help you out with that if you want, as I believe it can only make the experience of using an old computer less painful than with W7 ^^

**Comment by 613TheEvil** [comment]
Wow I didn't realize I was talking to the developer! My hat off to you, hehe. The thing with Franz is I could not find anywhere to ask questions like I am asking you now, to report bugs etc. I am getting zero notifications from Facebook messenger for example, it is an even bigger issue than no popups. I will try your fork, thank you.

**Comment by 613TheEvil** [comment]
And as for the usb OS... Again, I understand it is a good option but it would complicate things in my routine, let's fight one thing at a time better eh?

**Comment by 613TheEvil** [comment]
Anyway, back to Ferdium. Your fork is fine and I will use it, at least Facebook gives unread counter notifications, unlike Franz. But no popups. Perhaps it is for the best. I will set up shop in it, hehe. Thank you.

Edit! Oh, popup notifications work! If only for Whatsapp, at least. Facebook still has issues like Rambox had. No popups and when I write a message also a notification comes, on the unread message indicator. What a mess eh. At least I kind of notice when I have facebook messages, yeah.

**Comment by Alphrag** [comment]
Glad to see that it was helpful and that at least you can have some things working out well! 
To be honest, I think most people use the `Messenger` service for their messages instead of the `Facebook` one, and for the former there have been a few updates of the recipe to keep it up to date with the change of the website's structure, while the latter hasn't been touched in quite a while because there has not been any demand for it. So if you care about the private messages more than the actual website notification bubble, you should give the `Messenger` service a try.

**Comment by 613TheEvil** [comment]
Sorry, all this time I was referring to the Messenger service, of course. I just called it Facebook, in ancient times they were the same... Another issue I notice is that Whatsapp etc don't remember where you saved stuff the last time, they ask every time I guess, when I was on Rambox I could click the download button on Whatsapp and the photo or whatever was downloaded. I should double check Whatsapp service's settings actually...

**Comment by Alphrag** [comment]
Oh ok, then it means the problem is coming from the interaction of the old version of electron with Win7, since the actual version works well for me for all the OSes I am using Ferdium on.
As for the download, the cause is not with Whatsapp, but with us: giving a default download location is a feature that is not currently implemented in Ferdium, so we always ask the location to the user.

**Comment by 613TheEvil** [comment]
Yes obviously, I never tried Facebook on any of these multi-messengers. And to be honest too, I am not new, and I am tired of all the social media platforms treating computer users like shit. The only one that has an actual, functional, updating, backwards compatible program is Telegram. I am not sure about the state of the chinese ones, I have not used QQ etc. for years, but yeah... Line is not too bad either, the rest... Let's not expand.

**Comment by wefalltomorrow** [comment]
> Man, my pc is more than 15 years old, I don't think it gets any upgrades, I just keep it alive as is. For a new system, yeah linux is useful for certain things, for others... It can get in the way sadly, when you have to interact with other stuff coming in from windows and android environments. Anyway, the hibernation is fine, but what I wanted is not available sadly, the notification popups. I could use Ferdium 6.2.5 instead of Franz but, only for hibernation? I don't know...

$100 from your local online used marketplace will get you a PC that can run Windows 10/11 and Ferdium.

Otherwise you can try running Windows 7 Extended Kernel to see if Ferdium will run with it, but connecting an outdated and unsupported operating system to the internet with your private information on it is not a good idea.

Windows 10 LTSC is fairly lightweight and will run on any PC made in the past 10 years

**Comment by pepper3k** [comment]
> > Man, my pc is more than 15 years old, I don't think it gets any upgrades, I just keep it alive as is. For a new system, yeah linux is useful for certain things, for others... It can get in the way sadly, when you have to interact with other stuff coming in from windows and android environments. Anyway, the hibernation is fine, but what I wanted is not available sadly, the notification popups. I could use Ferdium 6.2.5 instead of Franz but, only for hibernation? I don't know...
> 
> $100 from your local online used marketplace will get you a PC that can run Windows 10/11 and Ferdium.
> 
> Otherwise you can try running Windows 7 Extended Kernel to see if Ferdium will run with it, but connecting an outdated and unsupported operating system to the internet with your private information on it is not a good idea.
> 
> Windows 10 LTSC is fairly lightweight and will run on any PC made in the past 10 years

The question was a technical one. Let's keep it technical. Not everyone has access to the same opportunites, let's try to be sensitive to that.

Also, there are many people that don't have the technical knowledge to do this, even if they have the money. 

In short, there will always be a use case and justification for pretty much everything, even if it's not money or technology.

**Comment by Alphrag** [comment]
> As for the download, the cause is not with Whatsapp, but with us: giving a default download location is a feature that is ~not currently implemented in Ferdium, so we always ask the location to the user~.

@613TheEvil I just realised I said something wrong last time... This shows how much things change and even I can't remember all the features we put in. It *is* possible to put a default download location, which you can find in the `Advanced` tab of the settings. By default it is empty, which means asking the user where to download the element, but if you select a path for your download folder, it will always download there. So if you set that up, it will be one less annoyance to take care of 😉

**Comment by 613TheEvil** [comment]
I understand, but it is a chore to have to select a folder every time you receive a picture or file, I noticed it on Messenger and Whatsapp too, so I guessed it had to do with Ferdium.

**Comment by wefalltomorrow** [comment]
> The question was a technical one. Let's keep it technical. Not everyone has access to the same opportunites, let's try to be sensitive to that.
> 
> Also, there are many people that don't have the technical knowledge to do this, even if they have the money.
> 
> In short, there will always be a use case and justification for pretty much everything, even if it's not money or technology.

Correct, hence why I mentioned Windows 7 Extender Kernel as well but also mentioned it's a privacy risk. If we're talking about technical things we shouldn't be recommending users to put their private data at risk, or at least give them a fair warning about doing so.

Either way, here's Windows 7 Extended Kernel https://github.com/vxiiduu/VxKex

A video overview/tutorial to help get it running: https://www.youtube.com/watch?v=zl7AsxtoPV8

**Comment by 613TheEvil** [comment]
> > As for the download, the cause is not with Whatsapp, but with us: giving a default download location is a feature that is ~not currently implemented in Ferdium, so we always ask the location to the user~.
> 
> @613TheEvil I just realised I said something wrong last time... This shows how much things change and even I can't remember all the features we put in. It _is_ possible to put a default download location, which you can find in the `Advanced` tab of the settings. By default it is empty, which means asking the user where to download the element, but if you select a path for your download folder, it will always download there. So if you set that up, it will be one less annoyance to take care of 😉

I got another issue I might need your insight for, even when I close Ferdium to the system tray, if I use the alt-tab menu, iit is still there. And alt-tabing also makes it appear on the taskbar too, minimized but still, without me really opening it. Any ideas?

**Comment by pepper3k** [comment]
Is this on windows? Can you reproduce it on another system?

On linux I can't reproduce this. Using KDE.

**Comment by 613TheEvil** [comment]
Yes we are still talking about Win7, sorry. And a particular Ferdium version.

**Comment by pepper3k** [comment]
is this reproducible on a fresh win7 system?

**Comment by 613TheEvil** [comment]
I don't know, mine is not exactly fresh... :P

**Comment by pepper3k** [comment]
someone needs to be able to reproduce the bug on a different system so that we can rule out a bug in the operating system and narrow it down to some sort of bug in the ferdium code. otherwise we might be trying to fix something that aint broke...which is a grave sin as everyone knows

**Comment by 613TheEvil** [comment]
I agree, there is no hurry, if somebody does that I will be grateful. I can't set up a new system to try it sadly.

**Comment by pepper3k** [comment]
what's the link to your specific build? i'll try it in a vm

**Comment by 613TheEvil** [comment]
https://github.com/Alphrag/ferdium-app/releases/tag/Win7-unsafe-v6.7.5-nightly.7 from further up this discussion thread here
