### ISSUE TITLE
macOS fails to start after latest recipe update

### ISSUE THREAD

**Issue by yarons** [ferdium/ferdium-app#1796]
I'm using 6.7.4 with the beta feature for refresh; the latest refresh crashed Ferdium so that it fails to launch completely.

Since it doesn't start, I don't know the exact recipe that caused it. Reinstalling from dmg solves the issue.

Working recipe versions (Before the refresh/upgrade):
WhatsApp: 3.5.6
Telegram: 3.4.5
Slack (disabled due to #788): 1.6.2

**Comment by code-n-go** [comment]
Same.  I understand this is beta; however, this is twice within a couple of weeks a release completely broke the app... implying a better QA process needs to be constructed and enforced.

**Comment by yarons** [comment]
I tried launching a mac on GHA for building and failed but I agree it is highly important.

**Comment by yarons** [comment]
Fixed in nightly.9 via #1798

**Comment by Alphrag** [comment]
> Same. I understand this is beta; however, this is twice within a couple of weeks a release completely broke the app... implying a better QA process needs to be constructed and enforced.

Hi @code-n-go, I understand that it can be frustrating that the app crashes. We locally build each change we make on at least two different computers to minimise this from happening. However, there are some steps which cannot be done locally in the same way that the github action does (such as notarizing the app), and some others that might happen to work locally but not on the github runners because of adjacent tools installed on our computers and that are not expected to come into play (this was the case last time when one of our dependency changed the way they built it without making the breakage clear in their releases). This is why we use these nightlies to try and catch such problems before they reach the larger part of our userbase that are running the stable versions instead, which are released fairly frequently. So if you prefer, you can disable the prereleases to stay on the stable versions.

Also, do not forget that we are all doing this on our free time, and try to make it work as smoothly as possible, but we don't have the resources to extensively test every time and on all platforms and even that may fail. So we are relying on people happy to be on the nightly builds to catch the problems we did not encounter during our test, and when this happens, we are trying to fix them as quickly as possible, so that Ferdium can always reach its best capabilities.

**Comment by Alphrag** [comment]
@yarons Just a small notice regarding creating an issue: please use the templates provided when creating it so that we can better understand what your problem relates to.
Also, using the appropriate words in their context will make your problem clearer to understand: the **app** Ferdium has three types of releases, which are the *nightly* versions (every time there is a change in the code, a new version is out), the *beta* versions (when we do a big change that has been in nightly for some time and want more users to try it -- this hasn't been used in a while), and the *stable* versions ("latest" version available by default on github); so that when you update the app it is from one of these version channels. Then, inside the app, you have the different **services** that you use (Discord, Github, Jitsi, etc...), which are defined in the backend by a set of files called the **recipe** of the service, relating to the url accessed, the colours of its dark mode, the code for how to find if there are notifications, etc. 
So, by saying that the app fails after the latest **recipe update** is not what you meant, because it was related to the **app update of the nightly version** instead. This also means that you were not on `6.7.4` but on `6.7.5-nightly.8` with the `Include pre-releases` toggled to on in your update settings.   

It is not much, but these differences on the term used can help us find the problem quicker and fix it without looking at the wrong place: I was not sure what you meant by your issue when you created it, and not saying exactly which `.dmg` you downloaded to fix this issue didn't help either. Thankfully it is now fixed, but if you need to create another issue some time in the future, that would be helpful for you to remember to give us these informations with the help of the template issues :slightly_smiling_face:

**Comment by yarons** [comment]
@Alphrag I had no idea what the cause is so I thought it was because of the recipes.
Regarding the version: noted.
