### ISSUE TITLE
Password Incorrect failed, help please

### ISSUE THREAD

**Issue by FatherGroup** [ferdium/ferdium-app#1863]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.5

### What Operating System are you using?

MacOS

### Operating System Version

Ventura 13.6.4Cuanto 

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.5

### Expected Behavior

Failed incorrect passwrod

### Actual Behavior

I installed the app on my mac and was setting it up, when I was in the security options and enabled password protection, the power went out and came back immediately. I turned on the mac, opened the app and it asks me for a password, but I never managed to enter any password. I deleted the app, put it back in and it still asks for a password. I would like you to help me remove this restriction, so I can configure it again, thank you.

### Steps to reproduce

Error open

### Screenshots

![Capture_Jul-23-2024_10 53 37](https://github.com/user-attachments/assets/4a8845a1-6c0f-404e-b257-f7f12276da6f)

### Additional information

I installed the app on my mac and was setting it up, when I was in the security options and enabled password protection, the power went out and came back immediately. I turned on the mac, opened the app and it asks me for a password, but I never managed to enter any password. I deleted the app, put it back in and it still asks for a password. I would like you to help me remove this restriction, so I can configure it again, thank you.

**Comment by Alphrag** [comment]
Hi @FatherGroup, in order to fix this, you will need to modify the configuration files by hand. First, make sure the app is closed as it might cause some troubles otherwise.
Then, we need to open the folder storing all the files that the app uses to store information.
- On a Mac: open a window in Finder and use to "Go to" menu to select the option "Go to folder..." in the dropdown (the usual shortcut for this is shift+cmd+G). This should open a small box in which you can enter a path to the folder we want. Enter the following: ~/Library/Application Support/Ferdium/ (whichever language your computer is in, this will go to the correct place).
- On a Windows: open a window in you file browser and click on the path of the folder to enter the following: `%APPDATA%\Ferdium`, which will be rewritten correctly to send you to the right place.
 
You now have two choices:
1. If you don't really care about any of the steps you did during your initial setup of the Ferdium app, then you can completely delete this folder, and starting the app after that will create a new version of it as if you were starting the app for the first time.
2. Otherwise, if you would like to try to keep some of the settings you had, then enter the `config` folder and open the `settings.json` in your favourite editor (the default text editor for example is fine). Then search for the lines containing the following keys in that file, and change them accordingly to match this setting (switching the `true` values to `false` in these lines):
```json
"isLockingFeatureEnabled": false,
"locked": false,
"lockedPassword": "",
```
After saving the file, if you restart the app it should now be unlocked, and you can then set up the lock again. If this doesn't work as expected, then do point 1. to remove the folder completely.

Let me know if this solves it.

**Comment by FatherGroup** [comment]
> Hi @FatherGroup, in order to fix this, you will need to modify the configuration files by hand. First, make sure the app is closed as it might cause some troubles otherwise. Then, we need to open the folder storing all the files that the app uses to store information.
> 
> * On a Mac: open a window in Finder and use to "Go to" menu to select the option "Go to folder..." in the dropdown (the usual shortcut for this is shift+cmd+G). This should open a small box in which you can enter a path to the folder we want. Enter the following: ~/Library/Application Support/Ferdium/ (whichever language your computer is in, this will go to the correct place).
> * On a Windows: open a window in you file browser and click on the path of the folder to enter the following: `%APPDATA%\Ferdium`, which will be rewritten correctly to send you to the right place.
> 
> You now have two choices:
> 
> 1. If you don't really care about any of the steps you did during your initial setup of the Ferdium app, then you can completely delete this folder, and starting the app after that will create a new version of it as if you were starting the app for the first time.
> 2. Otherwise, if you would like to try to keep some of the settings you had, then enter the `config` folder and open the `settings.json` in your favourite editor (the default text editor for example is fine). Then search for the lines containing the following keys in that file, and change them accordingly to match this setting (switching the `true` values to `false` in these lines):
> 
> ```json
> "isLockingFeatureEnabled": false,
> "locked": false,
> "lockedPassword": "",
> ```
> 
> After saving the file, if you restart the app it should now be unlocked, and you can then set up the lock again. If this doesn't work as expected, then do point 1. to remove the folder completely.
> 
> Let me know if this solves it.

Great, it worked, thanks for your help.
