### ISSUE TITLE
Feature: ad-blocker

### ISSUE THREAD

**Issue by maxecharel** [ferdium/ferdium-app#187]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

New to Ferdium (never used neither Ferdi nor Franz), I added an outlook service for a hotmail mailbox. I've realized that ads were displayed in my mailbox (I actually forgot the existence of such ads since in the past I've used thunderbird and then a browser + ad-blocker to access this mail account).

### Proposed Solution

Implementation of an ad-blocker

### Alternatives Considered

setting-up a Pi-Hole, the problem is that such an alternative would be restricted to my local network

**Comment by Jvlsc** [comment]
Probably duplicated #135.

**Comment by maxecharel** [comment]
@Dvlnst while #135 focus on password manager, you are right that it actually also mentions 'extensions' in general

**Comment by palepinkdot** [comment]
Closed as duplicate.

**Comment by stackcoder** [comment]
Since I genuinely want to give Ferdium a proper long-term try, I couldn’t overlook something as essential as ad-blocking. So, I’ve cobbled together a bit of a poor man’s linux only workaround:

I’m using the `LD_PRELOAD` library [userhosts](https://github.com/figiel/hosts), configured to point to my adblock hosts file. If you're on NixOS, it's quite easy to set up:

```nix
(ferdium.overrideAttrs (finalAttrs: prevAttrs: {
  preFixup = ''
    gappsWrapperArgs+=(
      --set LD_PRELOAD ${pkgs.userhosts}/lib/libuserhosts.so
      --set HOSTS_FILE /etc/adblock-hosts
    )
  '';
}))
```

Another option could be using an ad-blocking proxy like [privaxy](https://github.com/barre/privaxy). Of course, system-wide blocking via a standard hosts file, Pi-hole, or AdGuard would work just as well.
