### ISSUE TITLE
Slack locked in "Launching" screen (electron update required)

### ISSUE THREAD

**Issue by bastien-wink** [ferdium/ferdium-app#1916]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.0

### Recipe Name

Slack

### Recipe Version

1.4.2

### Steps to reproduce

Open any Slack

### Expected Behavior

Load slack web version 

### Actual Behavior

Stay in the loading screen with this message

Launching {my slack company name}
Click "Open Slack" to launch the desktop app.
Not working? You can also use Slack in your browser.

### Screenshots

![image](https://github.com/user-attachments/assets/8805dfd5-1433-47b9-bb38-24c1f77ab85b)

**Comment by bastien-wink** [comment]
I found the reason, Electron 25.2.0 comes with chrome 114 (june 2023), too old for slack.

**Manual solution** : I changed the user agent to Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0 
**Long term solution** : Update Electron

**Comment by Alphrag** [comment]
Hi @bastien-wink 
You are running quite an old version of the application, since 6.4.0 was released more than a year ago and we are currently at version 6.7.7 and using electron 32.x, so this problem is coming from your side. You should first make sure you are running the latest version of the app before raising an issue here. Thanks

**Comment by bastien-wink** [comment]
Ok, thanks.
So there might be an issue with auto updater : 

![image](https://github.com/user-attachments/assets/1c12a1c8-47a3-4401-9211-a16cd6e2e110)
It should not mention my services are up to date.

**Comment by Alphrag** [comment]
Which platform are you on, and how did you install Ferdium? Some targets unfortunately cannot be auto-uploaded from the application and they need to be updated by hand, or through a manager.

**Comment by bastien-wink** [comment]
On linux, manual install, I will move to snap.
We might want to not display the auto update button when it's not possible.
Thanks for your help :)

**Comment by Alphrag** [comment]
Yes unfortunately the auto-updater logic is not clean at the moment since we have many different targets and we would need to figure out on linux how the app was installed in the first place to either prompt the user to go to their package manager, or even to manually download the update when the auto-update cannot happen (currently only works for `.deb` and `.AppImage`, but others might happen). 
I have a few ideas for that but it's far from ready to be put into place...

At least going with the snap version, you will have access to the latest releases, you only need to choose which channel you want them from ;-)
