### ISSUE TITLE
The problem of using multiple Google mail through a Rumbox at the same time.

### ISSUE THREAD

**Issue by Silen7DM** [ferdium/ferdium-app#1953]
### Your issue

Hello friends. 
I ran into the following problem:
I use the rambox in order to have access to several of my GMAIL posts at once. I have 5 of them.
Recently, I can't use them at the same time, because when logging in to one mail, all the other 4 tabs in the rambox are logged in to the same mail. Now I can't log in to different emails at the same time. 

I thought the problem was that I had the free version, but unfortunately, the situation has not changed with the purchase. I've tried different versions and different computers. I tried another account in the rumbox. This problem is observed in all cases. I have been trying to solve this problem for over a week now, but I have little knowledge in this matter. Please help me.

**Comment by Alphrag** [comment]
Hi @Silen7DM, 
This repository is not at all associated with Rambox, so we can't help you with the problem you are mentioning and you would need to contact them directly to solve this. 

However, if you wish to replace Rambox by Ferdium, one thing I can say is that by default in Ferdium, each service you create is containerised, which means that you can create as many gmail services as you want with each of them acting in a complete separation to the others, so that you can log into multiple accounts without any problems. In fact, this is one of the main use some of our users have of this app.

**Comment by vraravam** [comment]
Another important point to note is that Ferdium is free for eternal use. No paid features at all.

**Comment by Silen7DM** [comment]
> Hi @Silen7DM, This repository is not at all associated with Rambox, so we can't help you with the problem you are mentioning and you would need to contact them directly to solve this.
> 
> However, if you wish to replace Rambox by Ferdium, one thing I can say is that by default in Ferdium, each service you create is containerised, which means that you can create as many gmail services as you want with each of them acting in a complete separation to the others, so that you can log into multiple accounts without any problems. In fact, this is one of the main use some of our users have of this app.

thanks for your reply. I will definitely take your advice. Thanks again for the help. I wish you all the best!
