### ISSUE TITLE
Ferdium 6.7.4+ -  not working on MacOS 10.15.7 Catalina

### ISSUE THREAD

**Issue by francwalter** [ferdium/ferdium-app#1966]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

7.0.0

### What Operating System are you using?

macOS

### Operating System Version

Mac OS 10.15.7

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.7

### Expected Behavior

Updates from a working version on MacOS 10.15.7 should not be allowed if it breaks the app, because it is not anymore for that OS version.

### Actual Behavior

When I updated Ferdium 6.7.7 to Ferdium 7.0.0 on my MacBook with MacOS 10.15.7 suddenly Ferdium stopped working, saying when I try to start:

> Auf deinem Computer ist macOS 10.15.7 installiert. Das Programm erfordert macOS 11.0 oder neuer.

(en: On your computer there is macOS 10.15.7 installed. The application needs macOS 11.0 or newer.)

I think I did every update on my MacBook, so I was on something like 6.7.7 (before the 7.0.0 update), which perfectly worked.
But after the update, which was proposed from in the app (bottom message), it stopped working.

### Steps to reproduce

1. Updates are checked in Ferdium 6.7.7 settings.
2. When an update is available, install it
3. Start Ferdium
4. Ferdium 7.0.0 wont start because it is not working under 10.15.7

### Additional information

I went then down to 6.7.3 ([Ferdium-mac-6.7.3-x64.dmg](https://github.com/ferdium/ferdium-app/releases/download/v6.7.3/Ferdium-mac-6.7.3-x64.dmg)) which is again working, seems to be the last version for 10.15.7.
But amazingly I had updated from there each version up (not nightlies) without any issue, only when I came from 6.7.7 to 7.0.0 it broke, and I was not able anymore to install 6.7.7. 
It seems that the check of compatiblity is ommitted on updates up to 6.7.7, only on new install it is checked and on 7.0.0 too, either on fresh install or on update.

But now most of the service-icons are missing, only those I defined myself (web service).

**Comment by Alphrag** [comment]
Hi @francwalter, 
The fact that Ferdium 7.0.0 does not work on MacOS version below 11 is not a bug, since it is something we know about and we have explicitly written about it in the changelog so that people could look at it (cf https://github.com/ferdium/ferdium-app/releases/tag/v7.0.0) by checking the "What is new?" link on the update banner before choosing to update the app. The check is not from us, but directly from `electron` on which Ferdium is built (since we didn't have any computer on hand running a MacOS 10.15, we didn't know what would be shown except from the fact that it might not work).

At the moment we do not have a check for the OS version that the user is running before updating, and this feature should be coming soon in the releases of `electron-builder` which we use to auto-update the app. We relied on users checking the information we provide in the changelog before updating, but if you wish to implement a failsafe directly in the code, we'll be happy to review it.

So the last version that should work on your OS is indeed [`6.7.7`](https://github.com/ferdium/ferdium-app/releases/tag/v6.7.7) (or [`6.7.8-nightly.6`](https://github.com/ferdium/ferdium-app/releases/tag/v6.7.8-nightly.6) if you are willing to use the latest nightly build possible in order to have the [custom/global sandbox feature](https://github.com/ferdium/ferdium-app/pull/1879)). 

The reason why you have missing icons is due to the fact you installed an old version of Ferdium in which the icons were stored locally, but this was later changed to fetch them on github directly and so are no longer present in your local folder.

**Comment by francwalter** [comment]
Thank you lottly for this thorrough explanation!!!
I immediately installed version 6.7.8-nightly.6 and it works 😄 
All icons back 👍 
I dont know how it happened, that when I tried to copy 6.7.7, 6.7.6, ... 6.7.4 it didnt work, only 6.7.3, but as you say, 6.7.8-nightly.6 works 👍 
If I knew that it could break I surely wouldn't had installed 7.0.0.
Good idea to implement such failsafe feature. I couldnt, I am no Mac programmer. 

_Anyway, Apple is quite strict with the must update macOS, I am on an old MacBook Pro from Mid 2009 (with the OS-Patch to 10.15.7), which is great, because its really good and long life hardware, its a real contrast to that update policy.
So in near feature I need to change hardware, despite of the still good working device._

Thanks, I will stay to 6.7.8-n.6 as long it works (and the other applications on my Mac).
