### ISSUE TITLE
Bug: Win11 Window manager does not detect/find ferdium

### ISSUE THREAD

**Issue by alecive** [ferdium/ferdium-app#220]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-beta1

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Ferdium version

none (it was happening with Ferdi too)

### Expected Behavior

Using `Alt-Tab` shows Ferdi and allows me to switch to it and put the window into focus.

### Actual Behavior

When I open Ferdium, it correctly shows up as an app both in my bottom window bar in Win 11 and in my window switcher when I do `Alt+Tab`. However, after an undescribed amount of time (it varies) Ferdium disappears from both. The only way I have to select Ferdium is to click on the icon in the taskbar which seems to spin up a new instance of Ferdium and then kill it right away. I suspect it's another Electron bug.

### Steps to reproduce

This bug is very hard to reproduce

### Screenshots

Ferdium working as intended (showing in window switcher and taskbar):
![image](https://user-images.githubusercontent.com/4378663/172733516-0f7a2088-86f2-4b8e-aaa4-4ab89cd528ad.png)

**Comment by SpecialAro** [comment]
Hello @alecive ! Thank you for raising this issue. 

I can see that you have Minimize Ferdium to system tray enabled. This causes the Ferdium window to collapse and leave the "explorer.exe" environment - which is why when you `Alt + TAB` it doesn't show up.

My personal opinion is that this isn't something that we can/should fix (maybe some other Dev has a different opinion) given the fact that this is a feature, not a bug (some users wan't Ferdium to minimize to system tray).

Can you try disabling that option or is it a requirement for you to have it on? If so, I can try to have a look to see if we can arrange a workaround.

@vraravam what do you think? can you give us your thoughts?

**Comment by SpecialAro** [comment]
Though, by looking into this even further I can see an issue:
After minimizing to tray and clicking to open Ferdium again, the window doesn't seem to be correctly resurrected (the taskbar icon stays as if not opened and it doesn't show up on alt+tab either)

![Animation2](https://user-images.githubusercontent.com/37463445/172824974-aea2f782-2408-4197-aad4-38e04f0a597a.gif)

So, there might be an issue after all.

**Comment by alecive** [comment]
Correct! Also, I have minimize to tray enabled but this happens when I don't minimize to tray. E.g. I have Ferdium open -> I select the browser without minimizing Ferdium -> I press Alt+Tab and Ferdium is not there any more. 

This is one of my most major usability issues with Ferdium. I had to change my workflow to accommodate for it because of how much I use and love Ferdium but it's a big pain in the butt so to speak :-) Also, it appeared with Ferdi too (and I suspect Franz as well) but none of the devs ever got back to me when I opened the issue---I'm hoping the third time is the charm!

I suspect it's a combination of factors (as it was working on Win 10), in particular how Electron handles window management and how virtual desktops are managed in Win 11.
