### ISSUE TITLE
Auto Update?

### ISSUE THREAD

**Issue by OskarEichler** [ferdium/ferdium-app#243]
### Your issue

Hey guys,

Great work on Ferdium! Just switched over and love it! I see there's pretty regular Nightly updates - but they don't seem to be passed through via the Auto Updater on the actual app?

Is that intended / a result of the missing developer license? Please let me know!

All the best,
Oskar

**Comment by SpecialAro** [comment]
Hello @OskarEichler , thank you for raising this issue.

This is currently a known issue caused, as you said, by the fact that the app isn't code signed yet.

We have already tested with self-signing and the update feature works properly so, we are currently analysing which way to proceed: pay for a code signing license for both windows and macos or self-signing.

**Comment by OskarEichler** [comment]
@SpecialAro Gotcha! How much is the code signing license? I'm sure we could raise that amount pretty swiftly!

**Comment by SpecialAro** [comment]
> @SpecialAro Gotcha! How much is the code signing license? I'm sure we could raise that amount pretty swiftly!

It depends I think 😄 @alphrag was looking into it and said something like: 100$ for apple and 50€ for a standard windows license. I think those are yearly costs.

**Comment by OskarEichler** [comment]
That should be doable - happy to cover that and then maybe have our company [Songstats](https://songstats.com) listed as a Sponsor in exchange. Let me know if that sounds good and send me a quick email of the person who's gonna handle the licenses. Our entire team used to use Franz & Ferdi, and we're glad to support Ferdium!

**Comment by OskarEichler** [comment]
Alternatively we also have an Apple developer account and could issue a license for you pretty quickly, but I assume you would like to use your own?

**Comment by macuser79** [comment]
I have an Apple Developer account if you want I can be of support

**Comment by Alphrag** [comment]
Heya. We are indeed currently discussing it with the team, but I can confirm that we already have tested the auto-update feature to work both on windows and mac (using self-signed certificates so far). @OskarEichler and @macuser79, thanks for the offer but it might indeed be better to have a certificate not linked to another company or a developer that is using it professionally to separate things. Getting this sorted is currently my priority as it is also one of the last things in #9 before a full release 🙂

**Comment by OskarEichler** [comment]
@Alphrag @vraravam @SpecialAro Hmm now that the Mac builds are officially signed I still don't get updates to the nightly builds? Currently on Build 75 and clicking on Check for Updates doesn't do anything - would expect it to download the latest Build 76.

Also it would be great to have an indicator somehow, that Ferdium is checking for updates and then give feedback if either everything is up to date or if there is an update that is being downloaded.

**Comment by vraravam** [comment]
@OskarEichler - we are able to see the updates. If you open the Settings view, click on the `Updates` tab, please ensure that you have the "Enable Updates" and "Include pre-releases" both turned on as shown in the figure below:

<img width="660" alt="Screenshot 2022-06-25 at 12 41 00 PM" src="https://user-images.githubusercontent.com/69629/175762826-4a778700-59ab-457e-91be-0743bef3bacb.png">

As Ferdium checks for the updates, there will be a spinner on that CTA button, and if a release is found, there should be a red decoration in multiple places. Please also ensure that you are running a signed version of Ferdium for this to work (if you have built it from source, it won't be signed, and so that update functionality wont work)

**Comment by Alphrag** [comment]
@OskarEichler The behaviour is exactly as expected: auto-updates are working from version 76 on Windows, in the sense that you need at least that release version installed for the next ones to come into place.
The reason is that previous versions were not expecting the publisher name to be what we have in the certificate (finding "Ambroise Grau" instead of "Ferdium Contributors"). You can check that the download happens but an error occurs and looking at the console you will see that it says the certificate is not signed by the expected publisher and will show you the certificate it finds. 
So one more to download by hand and then it'll all go fairly smoothly 😉

@vraravam In fact for Windows there is no need to have the current software signed for the auto-update to work since it doesn't verify that the certificates match (contrary to Mac), but it relies on the value of the CN of the certificate matching the `publisherName` listed in the `electron-builder.yml` config file.

**Comment by OskarEichler** [comment]
@vraravam @Alphrag Ahh sorry my bad guys! I didn't have the option to Include Pre-Releases enabled. I kind of expected that to be enabled by default when downloading the nightly/beta builds. Maybe that could be changed. Toggled it on now and everything is working as intended - great work guys!
