### ISSUE TITLE
Bug: unable to update/delete services on accountless mode

### ISSUE THREAD

**Issue by nathanaelhoun** [ferdium/ferdium-app#27]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Steps to reproduce

1. Use Ferdium without an account (text settings works with the brand new https://api.ferdium.org)
1. Go to service settings
3. Add a custom icon / edit everything else
3. Click "Save service".
4. There is a quick loading
    a. it was a custom icon ⇒ nothing happens
    b. it was another setting (i.e. the service name) ⇒ the service name is changed, but the change is lost on Ferdium restart

It is the same for a service deletion : after deleting it, it comes back if we restart Ferdium

### Additional information

There is a request made by Ferdium to `http://localhost:45570/v1/service/` (I'm using it without an account), with the updated service as the request payload.

But the response from the internal server is "Cannot read properties of undefined (reading 'settings')" with code 500.

App version (from `ferdium-git` AUR package)
![image](https://user-images.githubusercontent.com/45119518/164792026-0023bd3d-5c43-4858-98c5-77e14b8d0da5.png)

**Comment by vraravam** [comment]
I'm on the latest code, and am unable to reproduce this error.
<img width="284" alt="Screenshot 2022-04-22 at 7 38 34 PM" src="https://user-images.githubusercontent.com/69629/164838711-783adf18-d7ae-4327-8cfa-ca53d9bfe05f.png">

**Comment by Gaboris** [comment]
Can not reproduce on Win10 21H02 neither with Nightly 7 nor 10.

Is the internal server meant to use a different port on Linux or does it use them for different functions? I'm asking since the Export/Import menu is reached using `http://localhost:45569/` and trying to access `http://localhost:45570` just gives me a standard browser error.

**Comment by vraravam** [comment]
> Is the internal server meant to use a different port on Linux or does it use them for different functions?

From the code, the app just tries the next open port (starting at 45569 and incrementing by 1) while starting up the internal server. I dont think this is any different across OSes. Due to the unknown port (sometimes its not 45569), is why I had implemented the `Help` menu item to have a surefire way to reach the running instance of the internal server.

**Comment by nathanaelhoun** [comment]
I was able to reproduce on ArchLinux, with both `ferdium-git`, `ferdium-bin` and `ferdium` packages. 

Deleting a service returns error 500 with message `delete from services where serviceId = 'REDACTED' - SQLITE_READONLY: attempt to write a readonly database`.
With @vraravam's tip, the fact that port 45570 was used suggested me that I had something running on the background taking Ferdium's usual port. 

After a `sudo netstat -tulpn`, I found the culprit: other process of Ferdium was running on the background, and was locking the database file (hence "readonly database"). 
`killall ferdium` ⇒ Ferdium is now working correctly :+1: 

Thanks for your tip about the port, closing the issue :-)
