### ISSUE TITLE
Bug: missing release

### ISSUE THREAD

**Issue by Gaibhne** [ferdium/ferdium-app#311]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

not applicable

### What Operating System are you using?

Windows

### Operating System Version

not relevant

### What arch are you using?

x64

### Expected Behavior

Various things like the landing page and the webpage suggest that there is a proper release for Ferdium, but the GH releases/tags pages only list pre-release nightlies. Either a proper release is missing, or if there isn't one, the various download pages/links should indicate that one is to select a (which one, the latest?) nightly build, which usually I would think most people would not do unless specifically instructed to.

### Actual Behavior

A long list of nightly builds without further information as to whether one should be using nightly builds and if so, which one.

### Steps to reproduce

Go to https://ferdium.org/download or https://github.com/ferdium/ferdium-app/releases

**Comment by SpecialAro** [comment]
Hello @Gaibhne , thank you for logging this issue.

As you can notice on the website download page:
> We're in the process of getting direct downloads ready, for now you can follow the link below to download the latest nightly release of Ferdium from our GitHub Releases.

That's why all versions are marked as a pre-release for now, because there isn't a stable version published yet. On this note, I think @vraravam can clarify better this situation.

On this case, you should - of course - try the latest nightly (for the latest features and security upgrades), try the beta version we provide (which is several tags behind the nightly and might be unstable for using with the account version - accountless option is working ok) or wait for a proper stable release (which we are working full on towards that).

Nevertheless, I welcome you on board and invite you to try the latest nightly - which is surprisingly stable as users are reporting.

**Comment by vraravam** [comment]
I couldn't add anything more. Well put @SpecialAro . I would close this ticket with the above comments.
