### ISSUE TITLE
Bug: Toolbar not clickable in the horizontal area that OS level UI components plus padding use

### ISSUE THREAD

**Issue by BrianGilbert** [ferdium/ferdium-app#347]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.74

### What Operating System are you using?

macOS

### Operating System Version

Monterey 12.4 (21F79)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

unknown

### Expected Behavior

able to click in area of screen that service header UX is displayed

### Actual Behavior

Unable to click in this area

### Steps to reproduce

https://user-images.githubusercontent.com/114017/175430668-08fd3b3a-ed1d-4a95-86d7-d0a1a740d945.mp4

### Additional information

This affects all services

**Comment by wgordon17** [comment]
I'm having a similar issue now. I can't move the window by clicking in the top area. Also on macOS Monterey (12.4).

This only happens if the Ferdium window is _already_ active. If it's not the active window, then I'm able to grab the top and move the window around. But after the window becomes active, I'm no longer able to move the window. This occurs both with and without the navigation bar.

https://user-images.githubusercontent.com/22222756/175781449-d858e023-0ff9-4439-a5ab-773724d72c56.mov

**Comment by vraravam** [comment]
There was a bug where the draggable area on the top was present irrespective of whether the user had enabled it or not. The PR that fixed this issue had this fix in it as well. For you to enable the draggable area, you will have to turn it on in preferences first, and then you should be able to drag and drop.

**Comment by wgordon17** [comment]
Perfect, I found it in the preferences, and this indeed brought back the functionality I was expecting. Thanks 👍

**Comment by cino** [comment]
@wgordon17 You can check it again with that preference turned of the merged fix above enables dragging again without the extra bar. :) (Ofcourse,in the latest release)
