### ISSUE TITLE
App does not register/show as installed

### ISSUE THREAD

**Issue by SKJoy** [ferdium/ferdium-app#362]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.7

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 21H2 19044.1766 x64

### What arch are you using?

x64

### Expected Behavior

Installing the App with the installer .EXE from GIT assets should register the App as Installed and should show in the Add remove programs, as well populate the Start menu.

### Actual Behavior

Neither the installer creates an entry in the Add remove programs list, not it populates the Start menu.

### Steps to reproduce

Install Ferdium using the .EXE installer, strat up, then EXIT.
Open Add remove programs page, I don't find it there.
Open Start menu, I don't find it there either.

### Additional information

For me, it is an install over to use Ferdium :o I know I could create a shortcut to the installed executable, but that just doesn't seem right when I am installing an application :( Of course I had Ferdi installed before, and I tried uninstalling Ferdi, then reinstalling Ferdium, and my experience remains the same.

**Comment by SpecialAro** [comment]
Hello @SKJoy, thank you for logging this issue.

This happens because you didn't use the installer version of the app when downloading it, but the portable .exe version.

Please, [download here](https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.77) the latest nightly.

You should use the one listed as "Setup":
![image](https://user-images.githubusercontent.com/37463445/175764345-bbc351ae-5792-45d6-9bc1-2a794abcaecf.png)

Please confirm so that I can close this issue.

**Comment by SKJoy** [comment]
Hi @SpecialAro 

It was my mistake not to check out that SETUP label correctly. Please forgive me. This is a false bug report, and do you think you should remove this issue? :)

- Joy
