### ISSUE TITLE
Bug: No toggle for updating beta/nightly/experimental builds on Ubuntu 22.04

### ISSUE THREAD

**Issue by TJonCooper** [ferdium/ferdium-app#391]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.80

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Last Known Working Ferdium version

None - it has never worked.

### Expected Behavior

A toggle appears in the settings menu to allow for in-app updates for experimental/beta/nightly builds.

### Actual Behavior

No such toggle appears (see screenshots). There is currently no way I can see to update the app, besides downloading the latest .deb package (which was my original installation method). 

### Steps to reproduce

1. Go to Settings
2. Go to Updates

### Screenshots

![Screenshot-20220629145948-604x237](https://user-images.githubusercontent.com/15924377/176431940-0dcccd86-fff0-4f69-a774-f139354ddc88.png)
![Screenshot-20220629145937-551x200](https://user-images.githubusercontent.com/15924377/176431947-506f4a13-71e4-4355-b729-969f0a77eabe.png)

**Comment by Alphrag** [comment]
@TJonCooper can you try on the next nightly to see if the update works? We have made it available, but I fear that if you installed using the deb package, then it won't auto-update properly as the autoupdater of `electron-builder` expects to update an AppImage.
If you had installed the AppImage in the first place, the auto-update has been working fine since the start. 

The deb packages are a bit in a middle position between the standalone AppImage and the package manager versions such as flatpack, so I'm not sure how much will be feasible in the long run with these deb packages.

**Comment by TJonCooper** [comment]
@Alphrag Unfortunately - as you suspected - it does not work. It simply searches for an update indefinitely. I'd happily switch to the .AppImage if it wasn't for the inconvenience of needing to update the .desktop file. Would you recommend switching to the flatpak version?

**Comment by SpecialAro** [comment]
@Alphrag we may need the `if` statement after all, then :/
