### ISSUE TITLE
Question: Updater shows error when pre-release is not enabled

### ISSUE THREAD

**Issue by CorvusGei** [ferdium/ferdium-app#430]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.89

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Pro 21H2 Build 19044.1766

### What arch are you using?

x64

### Expected Behavior

"Check for updates" should work

### Actual Behavior

"Check for updates" returns the error shown in the screenshot

### Steps to reproduce

1. Go to Seettings
2. Go to Updates
3. Click "Check for updates"

### Debug link

https://debug.ferdium.org/6eaeb18b-fec0-4429-ae7f-5ed1e9cfa4e9

### Screenshots

![grafik](https://user-images.githubusercontent.com/101200194/177402761-dbfdf680-aa22-46af-b8ca-a7f5e055a03d.png)

### Additional information

I looked at my logs of the Pi-Hole - nothing was blocked, only some Microsoft Telemetry. So I think, that's not the problem.
Reboot and Installation of the actual build didn't work as well.

**Comment by Alphrag** [comment]
Hi @CorvusGei this is not really an error, but an expected behaviour (though the error shown is not very useful and we intend to come around to change that). Indeed, we currently don't have any full release yet, and since you haven't toggled the "Include pre-release" button, the auto-update fails to parse the content of the github release page as it searches for a stable release. 

So even though it is not really intended to give an error without further ado, it will work as expected as soon as we publish a stable release (and the update for pre-releases has been working fine for a while now).

**Comment by SpecialAro** [comment]
@Alphrag should we close this issue as it is not an issue (more like a consequence of not having a stable release yet)?

**Comment by CorvusGei** [comment]
Thank you very much for your fast response! I really didn't think about the  "include pre-release" button, although I saw, it is a nightly version. Sorry!
