### ISSUE TITLE
Nightly versions need different version numbers in Control Panel

### ISSUE THREAD

**Issue by russellbanks** [ferdium/ferdium-app#441]
On WinGet, the package version in the manifest needs to match the version that Control Panel shows for Ferdium, which is `6.0.0.0`. This means that even though Ferdium will be having nightly updates, WinGet won't alert the user to an update because the version on Control Panel is not changing. I would suggest that the Ferdium nightly versions have different version numbers in Control Panel in order to mitigate this.

_Originally posted by @russellbanks in https://github.com/ferdium/ferdium-app/issues/194#issuecomment-1177452576_

**Comment by Alphrag** [comment]
From my understanding, winget updates if the version of the current installed manifest is lower than the highest version in the manifest of the [Windows Package Manager Community Repository](https://github.com/microsoft/winget-pkgs), so that the version in the control panel is not really used at any point. But maybe I am mistaking somewhere and if you know more about that I'll be glad to learn about it so that we can setup all the versions accordingly :slightly_smiling_face: (though as said on the other issue, this shouldn't matter as we're getting rid of the `msi` installer, and the `nsis` one gives a correct value in the control panel)

**Comment by russellbanks** [comment]
> From my understanding, winget updates if the version of the current installed manifest is lower than the highest version in the manifest

The way that WinGet knows if there is an update is if the newest package verison is greater than the installed version (shown in control panel). Therefore, if the control panel shows `6.0.0.0` and the manifest PackageVersion is `6.0.0-nightly.91`, doing `winget upgrade` will always show Ferdium as needing an update, even when you are on the latest version.

Therefore, they should both be aligned. This then means however, that whenever there is a new update, doing `winget upgrade` won't show that there is an update as even if the location where it is getting the installer from is changing, it is still seeing it as the latest version (currently at least).

Of course if this isn't valid for the `AutoSetup*.exe`, then this shouldn't matter if it is to be changed.
