### ISSUE TITLE
Bug: Screen recording doesn't work for any service on macOS

### ISSUE THREAD

**Issue by pwlnk** [ferdium/ferdium-app#481]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.99

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Expected Behavior

Screen sharing works when permissions are granted to Ferdium.

### Actual Behavior

When I try to share my screen in any service (e.g. MS Teams, Discord) a pop-up shows up with a request to grant permissions to Ferdium to record a screen, even though it's granted. After choosing "Entire Screen" option in a service nothing happens.

### Steps to reproduce

1. Open Ferdium.
2. Open Discord/MS Teams service.
3. Join a call.
4. Try to share entire screen.

### Debug link

When I click "Accept and Publish" nothing happens.

### Screenshots

![Screenshot 2022-07-13 at 13 54 40](https://user-images.githubusercontent.com/7137780/178727781-f4e4388f-358b-41a9-9376-1029412a3146.png)

### Additional information

Seems to be related to #59

**Comment by Alphrag** [comment]
I had the same problem, which seems to be linked to some changes we have made in the authoring of the app, as it appears that my settings didn't recognise that Ferdium had the authorisation to record the screen, even though the app was listed as such.
It was quickly fixed by doing the following: remove Ferdium from `System Preferences -> Security -> Confidentiality -> Screen Recording` (or whatever name it is). Then, quit Ferdium, open again and try screen sharing. This should prompt the authorisation, which after toggling it in system preferences should ask you to close the app, reopen and then it should work.

@pwlnk Can you please try this and let us know if that works for you too?

**Comment by pwlnk** [comment]
After removing _Ferdium_ from _Screen Recording_ permissions and adding it again by opening the app, the screen sharing seems to work. Thank you for help! 👍 

Maybe it's worth to add such info to FAQ?

**Comment by Alphrag** [comment]
Good to see it worked for you. Good idea, I'll add something there.

**Comment by gnought** [comment]
The @Alphrag workaround does not work in macOS 13.1. Ferdium prompts repeatly after Quit and Reopen.

```
Version: 6.2.4
Server: Ferdium Server
Electron: 22.1.0
Chrome: 108.0.5359.179
Node.js: 16.17.1
Platform: macOS
Arch: x64
Build date: Sat Jan 28 2023 07:32:12 GMT+0800 (Hong Kong Standard Time)
Git SHA: 68e85c3e
Git branch: release
```
