### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by andrei93r** [ferdium/ferdium-app#488]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The darkmode on the services is very hit or miss , mostly not working at all

### Proposed Solution

Maybe impliment this chrome extension which is light on perf" 
"darkreader"

### Alternatives Considered

There is also another extension called midnight lizard however it heavy

**Comment by SpecialAro** [comment]
Hello @andrei93r. We currently don't support chrome extensions, so this will only be supported if we implement #135. Therefore, this can be considered as a duplicate issue.

If you think there is still an issue with darkmode on recipes, please open another issue and clearly describe what is wrong and which recipe is failing.

Also, next time, please read how to properly open an issue, given that the title of this issue is wrong.

Thank you!

**Comment by andrei93r** [comment]
> Hello @andrei93r. We currently don't support chrome extensions, so this will only be supported if we implement #135. Therefore, this can be considered as a duplicate issue.
> 
> If you think there is still an issue with darkmode on recipes, please open another issue and clearly describe what is wrong and which recipe is failing.
> 
> Also, next time, please read how to properly open an issue, given that the title of this issue is wrong.
> 
> Thank you!

Hi , I was not exactly suggesting to implimemt chrome extensions , more on the line to use thel same logic as that extension for the dark mode.
