### ISSUE TITLE
Bug: Chocolatey installation with --pre is broken

### ISSUE THREAD

**Issue by Gaibhne** [ferdium/ferdium-app#557]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

The version is the problem

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Pro 21H2 19044.1889

### What arch are you using?

x64

### Expected Behavior

When running `choco install ferdium --pre`, I expect it to install the latest nightly pre-release build, as described in the 'get ferdium' section.

### Actual Behavior

It installs an ancient pre-release:

```
C:\Windows\system32>choco install ferdium --pre
Chocolatey v1.1.0
Installing the following packages:
ferdium
By installing, you accept licenses for the packages.
Progress: Downloading ferdium 6.0.1.20220728-nightly-1... 100%
```

### Steps to reproduce

1. Open command prompt (admin)
2. Run `choco install ferdium --pre`
3. Contain your disappointment when you see it installs a very old version instead

**Comment by Alphrag** [comment]
Heya, for different reasons (mainly the way choco works with publishing new versions) we have decided to stop pushing the nightlies on chocolatey, and will only put the stable ones and the betas pre-releases. If you look at the website, it has been updated with that information a few days ago.
Since the auto-updates work well on windows, you could use it instead of a package manager to get the latest updates, but if you prefer to use one, then the `winget` package manager has all the stable, beta and nightly versions published there as it is much easier to maintain and is included in all new windows distributions. 

We try to provide Ferdium on as many package managers as possible but in order to keep the maintenance to a low level, we took the decision not to put all the releases everywhere. I am closing this issue since it is a choice rather than a bug, but feel free to ask if you have more questions.

P.S: as you can see, `choco` also does not like the naming of our pre-releases, and insert a timestamp instead of keeping the number at the end increasing, which makes it harder to figure out which version you are actually installing.
