### ISSUE TITLE
Bug: Whatsapp Web asks to be updated on every load

### ISSUE THREAD

**Issue by eitchtee** [ferdium/ferdium-app#572]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

Version: 6.0.1-nightly.17

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Expected Behavior

Upon clicking the message to update Whatsapp Web it should refresh and install a new version and not ask again until other update is available.

### Actual Behavior

Upon clicking the button to update, Whatsapp Web refreshes, but the version "installed" remains the same, getting asked to update again on a refresh of the page.

### Steps to reproduce

1. Activate a Whatsapp Web instance

### Debug link

https://debug.ferdium.org/42fb4293-0162-4f6c-bad6-131b3a078f0d

### Screenshots

![image](https://user-images.githubusercontent.com/10510126/186662660-a0902237-f150-40c5-982e-df81a5307175.png)
Message to update every time Whatsapp Web is loaded

![image](https://user-images.githubusercontent.com/10510126/186662746-cfd6036c-2f02-4a88-b3b3-1d3a3e1080ff.png)
Whatsapp Web version before updating

![image](https://user-images.githubusercontent.com/10510126/186662831-fb4cad28-c66e-4a36-9b32-38a51237c189.png)
Version after updating

### Additional information

It's worth noting that when I open Whatsapp Web on a browser, it runs on the same version as the one installed on Ferdium (v. 2.2230.15), but no update message is displayed, meaning this could be related to Ferdium itself not passing the correct information on storing required information.

**Comment by eitchtee** [comment]
This was mentioned on #535 but not given attention due to other problems on the same issue.
Also ferdium/ferdium-recipes/issues/32

**Comment by eitchtee** [comment]
Looks like this fixed itself, running v.2.2232.8 right now and no prompts.

**Comment by DeN-AlB** [comment]
The issue is still not fixed on my side. Just installed Ferdium and added WhatsApp. On every start, the message appears that there is an update for WhatsApp available. :(

------------------------------------------------------
Version: 6.1.0
Server: Ferdium Server
Electron: 20.1.0
Chrome: 104.0.5112.102
Node.js: 16.15.0
Platform: Windows 11
Arch: x64
Build date: Sat Aug 27 2022 01:40:44 GMT+0200 (Mitteleuropäische Sommerzeit)
Git SHA: 117ea8b2
Git branch: release

**Comment by vraravam** [comment]
Please do not continue to post messages on this topic. The "Update available" as per the attached screenshots is something that WA is triggering from the server-side. we will not be able to patch that at all. The only mechanism that might sort of fix the problem (albeit temporarily) will be the play around with the user-agent - try for the Chrome browser in your OS, since most websites seem to optimize for Chrome.

**Comment by DeN-AlB** [comment]
I'm using Franz in parallel, and I'm wondering that in Franz these Updates are not available. Just updated to Ferdium 6.2.0 and the "Update available" message is back again on every start. Just wanted to mention this ...

**Comment by francwalter** [comment]
I tried user-agent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 13_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
on my Mac with 10.15.7. The message is still there. It disappears if I click to Update, but it doesnt update, which is clear.

I had this issue on Hamsket too, but there it was not possible to even temporarily get rid of it. But Hamsket is out of development since a while and I guess it is also relevant which electron version is inside.

I wonder why it is not possible to get rid of it with some user.css or user.js, could catch it with some (DOM) search for the content "Update available" or "Update verfügbar" in german:

![grafik](https://user-images.githubusercontent.com/927269/226539187-7e0ec62a-18ed-40e7-b21a-295f5568153f.png)

It is not possible for the user, because I cannot use Dev.Tools inside the webview element, need to be done by app-devs.

It is not a big deal, when it disappears at least temporarily, but if it is alway there it is annoying because it uses important space there.

EDIT: I was wrong, I can indeed look into the code of the webview, with the Service Developer Tools (in View menu).
So I found the chat-butterbar as the culprit, I try now to displaynone it with that code in my user.js:

```
module.exports = (config, Ferdium) => {
  // Write your scripts here
  // 2023-03-25: warten bis Seite fertig geladen ist...
  window.addEventListener("load", (event) => {
    try{
      hideUpdateMessage();
    } 
    catch(e) {
    // nothing to do
    }  
  });  
  // zur Sicherheit noch mal mit Interval (delay in ms)
  var delay = 60000;
  setInterval(hideUpdateMessage, delay);
  function hideUpdateMessage() {
    try{
      document.querySelectorAll('[data-testid="chat-butterbar"]')[0].style.display = "none";
    } 
    catch(e) {
    // nothing to do
    }
  }
};
```
Dont know if that works though, as the Nag-message comes and goes (with every reload).
Posted the same code also here: [Update available - get CSS or TagName of DIV](https://github.com/vednoc/dark-whatsapp/issues/199) but I guess here is the better spot, also the dark-whatsapp repo is a bit silent :smirk: 

EDIT 2023-03-27: ok this seems to work with setInterval and hide the chat-butterbar :smile: 
Since I done it this way, no more Update available (visible). Hope it stays this way...
