### ISSUE TITLE
Bug: WhatsApp Open Graph Data not loading

### ISSUE THREAD

**Issue by shaneoreilly** [ferdium/ferdium-app#615]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

macOS

### Operating System Version

13.0 Beta (22A5342f)

### What arch are you using?

x64

### Expected Behavior

When adding a message in Whatsapp, opengraph data gets pulled in from the URL
Image, title, description etc

(This screenshot is using the native Whatsapp app)
<img width="730" alt="Screenshot 2022-09-14 at 16 26 52" src="https://user-images.githubusercontent.com/15385374/190255570-22b91c22-991d-4e07-b1cc-c998c56dc34f.png">

### Actual Behavior

In Ferdium, the opengraph data isn't being retrieved

(This screenshot, is the same URL in Ferdium)
<img width="789" alt="Screenshot 2022-09-14 at 16 27 38" src="https://user-images.githubusercontent.com/15385374/190255747-78b0b1a1-28a7-4b4c-9a67-a2ff0d614385.png">

### Steps to reproduce

Add Whatsapp as a service
Send a message, with a URL that contains opengraph data

**Comment by vraravam** [comment]
This isn't behavior that we can control in Ferdium.

If the intended behavior is working find when using a normal browser and hitting the web page for whatsapp, then I would suspect that it could be a problem due to the browser detection algorithm on the server-side. If so, then max that we can suggest is to use a different user-agent string for your whatsapp service (can be set from the UI by right-clicking on the service, and choosing `Edit`).
