### ISSUE TITLE
Feature: mobile app or webapp

### ISSUE THREAD

**Issue by mybuntu-git2** [ferdium/ferdium-app#650]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There is no mention about the existence of a mobile app or webapp for ferdium

### Proposed Solution

I guess if none exists, the next best thing is a webapp that renders into mobile phones and that we can run from e.g. a Linux server

### Alternatives Considered

Stream ferdium desktop, but that will not allow local notifications and is substantially heavier

**Comment by vraravam** [comment]
`Build cross-platform desktop apps with JavaScript, HTML, and CSS ` - this is what Electron itself espouses, and since Ferdium is based on electron, I don't think we will be supporting a mobile app in the near future.

lol - Ferdium is a webapp that's used to include other webapps inside it. Having ferdium itself be a webapp, seems kind of incestuous in some weird manner.

**Comment by theoden8** [comment]
Hi, I've built something similar for mobile platforms only, using flutter inappwebview
https://github.com/theoden8/webspace_app
I'm an addict of ferdium and I needed its functionality on my phone, too
