### ISSUE TITLE
Bug: Hotkey CTRL+PLUS doesn't Zoom in on content

### ISSUE THREAD

**Issue by SpecialAro** [ferdium/ferdium-app#669]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.17

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Whilst in Ferdium, click `CTRL + Plus (+)` to zoom in on service content.

### Actual Behavior

`CTRL + Plus (+)` doesn't zoom in on service content.

### Steps to reproduce

1. Open Ferdium
2. Press `CTRL + Plus (+)`
3. See that the content doesn't get zoomed in.

### Additional information

Come to the conclusion of this issue while closing this one: https://github.com/ferdium/ferdium-app/issues/668

This may be due to some problem with the `accelerator` key on the menu.

**Comment by vraravam** [comment]
I'm able to use `Cmd+plus` and `Cmd+-` on macos to zoom in and out without problems.

**Comment by SpecialAro** [comment]
Ok, so this might be a Windows only issue. @Alphrag would be able to test on your Windows machine just to make sure it is not something on my local?

**Comment by Alphrag** [comment]
[tldr; this a problem coming from how electron interacts with Windows keyboard layouts.]

After a few tests on my Windows version, it appears that this is not consistent across different keyboard layouts: if I set the UK layout, then I have no problems whatsoever. However, other layouts such as French (windows or mac layouts) or Swiss (windows or mac layouts) give inconsistent results. 

[I will use `&` to mean pressing keys jointly for clarity.]
For example on the French one, the `-` sign is located on the same key as the number `6` but is the primary character (we need shift to use numbers), but typing `ctrl & -` acts instead as `ctrl & 6` (change to 6th service). In the same way, `ctrl & à` acts as `ctrl & 0` since `à` and `0` are on the same key. However, for the zoom in, `+` and `=` are on the same key with `=` the primary character, and there we do need to use shift (so doing `ctrl & shift & =` in order to act as `ctrl & +` as expected.
On the other hand, for the Swiss keyboard, `ctrl & -` and `ctrl & 0` works as expected (both are primary character of their respective keys), but the `+` is located on top of `1` and thus needs shift cannot be combined with the `ctrl` key as expected: `ctrl & 1` does the change to the first service as expected while `ctrl & shift & 1` which should act as `ctrl & +` does nothing. 

Another thing interesting is that not all layouts are recognised appropriately: using the Mac layouts of languages fails when activating hotkeys and automatically uses the Windows layout, when it does work on other app (such as firefox which has the same hotkeys for zooming in and out). However typing into any text boxes is as expected with the correct layout selected. 
This problems doesn't just concern us, I have tested on Discord which suffers of this (though they are soooo far behind on updating the electron they use, it might not be the best test example), so I am not sure if it is coming mainly from electron, or from Windows itself (built by default for US keyboard layout).

**Comment by vraravam** [comment]
Thanks for the detailed info @Alphrag . I vote that we tag this as an upstream bug, which we can't really fix. We can still keep it open for tracking purposes. wdyt?

**Comment by Alphrag** [comment]
Yeah I agree with you @vraravam. When we will make the hotkeys configurable by the user, hopefully this will solve that problem, but I'll open an issue on electron and see what they say about that.

**Comment by SpecialAro** [comment]
Thank you for that detailed info @Alphrag ! Indeed, I never thought about that... In fact, I use a Portuguese Layout, therefore that might be the case of the problem you described.

I agree with keep this open just for tracking purposes, even though we now this isn't really our problem to solve but Electron's.

@Alphrag let me know if you need any help on opening this issue on Electron 😄

**Comment by J-Kappes** [comment]
I have the same issue on Fedora 36 GNOME 42.5. (Flatpak)

**Comment by vraravam** [comment]
Is this related to #250 ?

**Comment by Alphrag** [comment]
> Is this related to #250 ?

It seems that this other issue also relates to the fact that one needs to make a full reload of Ferdium after adding services to be able to use the hotkeys, so they are in my view a bit different (we could fix that that displaying a message that Ferdium should to be reloaded after adding a service/workspace).

**Comment by workingj** [comment]
Same here:

`Ctrl MouseWheel` does not work

`Ctrl -` does work

`Ctrl +` does not work
`Ctrl Shift +` does work instead

OS: Pop!_OS 22.04 LTS x86_64 
DE: GNOME 42.3.1 
WM: Mutter 
German Keyboard & Layout

**Comment by mareknovotny** [comment]
i can't zoom in/out on Ubuntu 23.04 too and i don't recall when it actually worked in past versions.
The only zooming works from menu which is annoying.

Also extending this I am surprised that Zoom is not preserved when the service is reloaded or Ferdi is restarted. 
My services GChat, Slack, Zulip.

**Comment by Abba-** [comment]
Hi newbie here on windows.
Confirming on windows only the regular - and (shift) + works i.e. ctrl with numpad +/- doesn't change zoom.

Also, split view doesn't necessarily zoom on the last one service I clicked.  I have to make sure to select the corect service on the left.

**Comment by kikislater** [comment]
Any idea where the zoom is stored in preferences ? 
Electron and "zoom -" doesn't work on french layout keyboard without numpad

**Comment by workingj** [comment]
hi, i hit `ctrl` + `shift` + `+` and it did the opposite, i zoomed out way too much
and i cant zoom in anymore, zoom function seems to be broken for me...
Edit: Ok, it is only messed up in github sevice...

**Comment by SpecialAro** [comment]
> hi, i hit `ctrl` + `shift` + `+` and it did the opposite, i zoomed out way too much
> and i cant zoom in anymore, zoom function seems to be broken for me...
> Edit: Ok, it is only messed up in github sevice...

You can use the View Menu for that 😁

**Comment by mareknovotny** [comment]
btw i found this issue on electron https://github.com/sunner/ChatALL/issues/325#issuecomment-1615730998, which seems is what works for me
Specifically `Ctrl` + `Shift` + `=` 
is there a mixed/wrong shortcuts shown in the menu?
