### ISSUE TITLE
Bug: Services look blurry

### ISSUE THREAD

**Issue by Zahrun** [ferdium/ferdium-app#716]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Other Linux

### Operating System Version

Kubuntu 22.10

### What arch are you using?

x64

### Expected Behavior

Service is clear

### Actual Behavior

Service is blurry

### Steps to reproduce

1. Use ferdium

### Screenshots

![image](https://user-images.githubusercontent.com/10415894/198669470-2205e6a0-6edd-4080-ab96-bb31f42536ec.png)
On the left-side, WhatsApp in nativefier (also using electron), on the right-side, WhatsApp in Ferdium.
Same thing happens in any service

**Comment by Zahrun** [comment]
Actually, everything in the service looks blurry, including images.

**Comment by Zahrun** [comment]
Figured out that it is because I use the Force font DPI to 108. If I set the setting back to default DPI, after restart of Ferdium, the services show correctly, even though smaller. It looks like Ferdium is not scaling properly according to DPI.

I’m on X11

**Comment by vraravam** [comment]
The screenshot is of the service itself. This rendering/resolution is not something that Ferdium can control. All Ferdium is doing is showing a webpage in Chromium. Closing.

**Comment by travnick** [comment]
@vraravam So why in Chromium (the left, 111.0.5563.146) the fonts are sharp, but in Ferdium are not?
Additionally, the settings of Ferdium itself is also rendered nice and sharp.

![image](https://user-images.githubusercontent.com/619590/229084391-2312c28a-fcf6-4362-8698-1b37d0429296.png)

```
screen #0:
  dimensions:    5120x1440 pixels (1102x313 millimeters)
  resolution:    118x117 dots per inch
```

```
Version: 6.2.6
Server: Ferdium Server
Electron: 23.2.0
Chrome: 110.0.5481.192
Node.js: 18.12.1
Platform: Linux 6.2
Arch: x64
Build date: Fri Mar 31 2023 10:51:49 GMT+0200 (czas środkowoeuropejski letni)
Git SHA: 28d1f763
Git branch: makepkg
```

@Zahrun What exactly did you change?

---edit:
What's more, since slack-desktop and Ferdium both use electron, then it both should look the same, but they are not.
Additionally, starting `fedrium` with `--force-device-scale-factor=really_any_value_here` fonts are looking sharp. It really does not matter what value I use there, the fonts are sharp - of course the size (scale) changes.

In this case I suppose that Ferdium is doing, or maybe is not doing something that is important to properly render sharp fonts.

**Comment by Zahrun** [comment]
Just to clarify, I didn't find a solution to have Ferdium render fonts properly when DPI is anything different from 96. What I did was just come back to 96 dpi, which looks fine on my screen, but other screens definitely would require Ferdium to render fonts properly at any set dpi. I don't know the specifics why it is not already doing that. 

With --force-device-scale-factor=1, it renders well (at 96dpi) whatever be my screen setting. If I set it to 1.125, it still looks blury in any case.

**Comment by travnick** [comment]
@Zahrun The HiDPI (I guess any other than 96) is quite tricky and not very mature yet to work out of the box.
I have a few fixes suggested here https://wiki.archlinux.org/title/HiDPI applied in my system
```
~ $ cat /etc/profile.d/hi_dpi_fixes.sh 
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export PLASMA_USE_QT_SCALING=1
export GDK_DPI_SCALE=1.23
```
