### ISSUE TITLE
Why is portable spawning a temporary exe?

### ISSUE THREAD

**Issue by AtmanActive** [ferdium/ferdium-app#724]
### Your issue

Hi,

I'm using all portable apps on my windows, some natively portable, some made portable by [portableapps.com](https://poatableapps.com) or [portaps](https://portapps.io/). Apart from runtime libraries and drivers, I have nothing installed on my windows.

Hence, I was happy to see Ferdium-portable offered for download.

But, unlike any portable app that I have and run daily, Ferdium-portable is spawning a random temporary exe each time it runs?!?
Why is this?
Only viruses behave like this.
This totally messes up the security on the system.
There is no trusted, fingerprinted exe in a specific location which can be fully trusted, but there is a random exe showing up at random path always asking for new permissions every time it is run.

It is unusable like this.

Is there a way to make it run like a normal portable app?

Thanks.

**Comment by Alphrag** [comment]
Hi @AtmanActive, sorry about this weird behaviour which is coming from the way `electron-builder` deals with it. Indeed, they provide the opportunity to have a "portable" version when building, which we thought was good enough (I tested it and moved it around without problem) but we didn't go deep into how this was handled. 

Their [documentation on this is really lacking](https://www.electron.build/configuration/nsis#portable) (to say the least), but from what I understand [directly from the code](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/nsis/NsisTarget.ts#L261-L268), it [appears that it does unpack](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/portable.nsi) it in the `TEMP` folder with a name that can be set.
At the current stage, that name is linked to the UUID of the build. We could make it fixed to a given string if you think that would be useful, with the caveat that if two instances are launched they will use the same unpacked folder, and when one closes it is going to delete it, which can cause trouble on the other instance. If you are interested in that approach, we could try it to see it that would be useful for you, but at the moment being, we can't do more than that on our side, and you would need to request a change to `electron-builder`.

**Comment by AtmanActive** [comment]
Hi,

Thank you for considering a fix.

What is curious to me is that I have plenty of Electron apps on my desktop behaving 100% politely in portable mode.

I think the confusion here stems from what exactly someone defines as portable.

What you are describing is actually a portable read-only mode. The premise here is that the software assumes that it is running from a read-only media, or otherwise restricted media and therefore has to spawn a runtime exe in a well-known location to make sure it would run at all.

On the other hand, windows Portable revolution introduces exactly the opposite: a Portable app should never ever assume any well-known location, but should write it's data and config files exclusively in the folder from where exe was started or a subfolder there of.

So, when an app runs as a proper windows Portable app, the first thing it needs to do is to discover the running folder. No settings, no pre-defines, no shortcuts or assumptions. Just a simple one-liner in the code that says "my working folder is now the folder where this exe was started from". After that, a developer can concatenate a subfolder name, if they so wish, like, for example "data" or "settings" or "profile" or whatever, and use that path for all loading/saving while running. No need to spawn any other exe. No need to touch the underlying running system. No need for registry. No need to assume anything about anything.

Hopefully, you will consider this approach.

Some Electron apps I have running in Portable mode would require a simple runtime command line switch to run like this, which is fine. That way a single codebase, a single exe can be used in both scenarios.

Thanks!

**Comment by AtmanActive** [comment]
And to answer your question: yes, if spawned exe would stop changing it's filename, that would be beneficial, even if it spawns itself in windows temp folder. It would be weird, but usable.

**Comment by AtmanActive** [comment]
For example, here is how I run Atom IDE in portable mode on my windows.
I have a .bat file with the following:

`set ATOM_HOME=A:\MyPortables\Programs\Develop\Code\Atom\.atom`
`START atom.exe`

and then, in my portable shortcuts, instead of running atom.exe directly, I just run this bat file.

I found this recipe several years ago and been using it ever since. Now I see there is even a dedicated repo (I didn't have a chance to try this one yet):

[https://github.com/garethflowers/atom-portable](https://github.com/garethflowers/atom-portable)

**Comment by AtmanActive** [comment]
And just to clarify why I'm so devoted to Portable software paradigm on windows:

For me personally, running setup.exe is a tremendous waste of time. Backing up, restoring my files and watching Microsoft destroy my digital life with each new PC is, also, a tremendous waste of time. So, for me, windows registry is evil, well-known user paths are evil, %APPDATA% is evil.

I want to be able to perform my app configuration **_ONCE_** and have it ready and willing for the rest of my life.
Portable software paradigm on windows gives me just that (same like how server administration on linux works much in the same way).
Hence, twenty years ago I dedicated a disk drive to this cause, assigned it to letter A: (since floppy disks are not in use anymore) and wherever I plug my drive into, I can immediately run all of my software, find all of my files, launch all of my icons and shortcuts and desktop goodies. Thus, for me, windows is just an on-hardware layer with few drivers, runtimes and tweaks here and there. This enables me to switch PCs every few months, to easily propagate my own programs and documents to any machine I wish, and to keep it intact forever and ever.

I mean, think about it, what's the point in windows offering you well-known locations when everyone and their dog can write to them. Windows documents? What a joke! Few months later and you'll find stuff you never needed or wanted there written by who-knows-who. Also a perfect target for ransomware and other malicious code.

Now, not all software can be fully and truly portable. That's why I'll accept any usable level. It is about relative paths and the ability of the app to read/write it's config to a dedicated folder instead of writing it to registry or a well-known windows folder.

- Some apps can figure out their working exe's path without anyone writing it down somewhere for them - these are truly portable
- Some apps can load/save from/to a user-defined location but have to have an absolute path for that - these are half-portable but still usable (since I'm not changing their drive letter or location often)
- Some apps are wrapped in helpers to achieve this, as seen on [portableapps.com](https://poatableapps.com/) or [portapps.io](https://portapps.io/)
- Some apps are simply impossible to portablize, and, of course, I stay away from them. These include apps requiring Program Files, requiring custom DLLs injected into windows/system32, apps writing their settings to registry, apps installing their parts in several different paths, and so on.

Yes, it is a never ending struggle when it comes to adding a new app, but I find it worth it.
My PC is my own **_Personal Computer_**. Personal in every way. And rock solid. And surviving the sands of time that are always working to erase everything we did and make us forget the path we were on.

Thanks!

**Comment by Alphrag** [comment]
Hi, I fully understand your point of view and I agree that it would be best to have proper portable apps. This is why we enabled the `portable` option in `.electron-builder` to create it. It is not because some other electron apps have a correct portable version that we can do the same easily. The maintainer of the package electron-builder that we use to build our app made a choice on what they see as an app being portable, and we cannot do anything about that decision. The behaviour they chose is that you can carry that exec somewhere else and it will always save the information into a folder where it is located (so you don't need to tell it where it lives, it does that by itself and look for the settings at the same path), but in order to be sure that this is run appropriately on the system itself, this exec span a temporary one by unpacking itself in some directory (that can be forced, or it naturally looks for the environment variable that gives the default temporary folder of the system). At no point paths are hardcoded, and everything is done at run-time. This indeed means that you cannot create shortcuts to that exe, but I guess that the developer view on portable was that if you want such a shortcut it is because you run it often, in which case you should likely install it completely. Different philosophy, thus different structure.

Anyway, if you want to submit a feature request [directly to the team behind electron-builder](https://github.com/electron-userland/electron-builder), feel free to do so, but the only thing we can easily change here is to prevent the unpacking from generating the folder name using the current UUID, but to give it a fixed one (this won't mean the exec location is hardcoded, but at least using your environment variables you will have the first part of the path, and only the folder name for the unpacked exe will be the same).

 
> What is curious to me is that I have plenty of Electron apps on my desktop behaving 100% politely in portable mode.

If you have any that are open source, we could look at the code on how they created it, and if that is something that would require relatively small changes on our end (unlike the building process of atom which is complicated to get to and to maintain), then we might consider trying to make such a build. But I cannot promise anything about that since it is currently not on our priority list and it would likely mean changing most of our building process, which would need thorough tests once again. Of course, we are always happy for any PR if you manage to do it on your end 😄 


> * Some apps are wrapped in helpers to achieve this, as seen on [portableapps.com](https://poatableapps.com/) or [portapps.io](https://portapps.io/)

In the meantime, you probably could try to see if these would give you a better result at having a standalone app.

**Comment by AtmanActive** [comment]
Hi,

Thank you for considering this.

I think that the first step should be to stop the spawned exe from randomly changing it's name.

You mentioned that the path of the spawned exe can be forced. If there would be an option for an end-user to supply the desired path that would be excellent. So, either as a command-line argument, or as a specialized environmental variable. If none found, then, spawn the exe in the well-known-windows-temp-dir. But, if there is a path found in either a command-line argument or a specialized environmental variable, then, check if that folder exists, and if does, spawn the exe there. Presto! All use cases covered.

The reason why I'm investing my time in explaining all of this here is that, I believe, Ferdium is the only one continuing moving forward. All others have been abandoned, including Rambox, Franz and Ferdi, so if I decide to go with one of them, I'm stuck with the last available version forever (I do have them in portable versions).

Thanks.

**Comment by Alphrag** [comment]
Yes, it seems that something should be possible for the path. Indeed, looking [at the code of how a portable](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/portable.nsi#L33-L36) is constructed and behave:
```nsi
StrCpy $INSTDIR "$PLUGINSDIR\app"
  !ifdef UNPACK_DIR_NAME
    StrCpy $INSTDIR "$TEMP\${UNPACK_DIR_NAME}"
  !endif
```
I assume that it could be possible to force that in a way or another. Personally, it goes into the path stored at `$env:TEMP` but modifying it and then spawning the portable via `$env:TEMP=The\path\I\want && C:\path\to\portable.exe` doesn't seem to do what I want. I personally am a unix person so I don't fully know the ins and outs of how windows apps work through nsi. I'll leave you to try to see if you can force the path of that folder through an environment variable on your side, and I'll look into changing the name of the unpacked folder.

**Comment by Alphrag** [comment]
@AtmanActive I have finally found where this was supposed to be modified in order to get the desired behaviour (nowhere to be seen in the documentation). The directory will now be located at `%TEMP%\Ferdium-Unpacked`.
Could you please test it and tell me if that is what you expected either by building it yourself or by waiting for the PR to be merged and the following nightly to happen?

**Comment by vraravam** [comment]
Though I haven't tested this on a windows machine, the code looks good. Have merged this so that the upcoming nightly in a few mins will have this fix. We can test it soon after.
