### ISSUE TITLE
Question: user.js usage & missing wiki

### ISSUE THREAD

**Issue by SelfRef** [ferdium/ferdium-app#842]
### Your issue

Hi,

I try to alter behavior of service using `user.js` file that's support was implemented in [this commit](https://github.com/ferdium/ferdium-app/commit/ce988c280f5ca6dfc202d209e66d7cfce257c43b).

Although using methods like `console.log` works and logs are visible in the console under Service Development Tools, it looks like modifying `window` object or global scope in general in script does not make any effect. I'm not sure how to access global scope of the service page. It looks like some property under `config` or `Ferdium` parameter may be the target for service window scope but I cannot find any information about these objects structure.

This is example script:
```js
module.exports = (config, Ferdium) => {
  // Write your scripts here
  console.log("Hello, World!", config, Ferdium);
  window.test = 'test'
  test2 = 'test2'
  console.log('test3')
};
```

Output in service's console:
![image](https://user-images.githubusercontent.com/69125050/207876041-a71a8297-e115-497b-92b3-7d95639b23bf.png)

As visible on screenshot the script does execute and variables are probably written somewhere but it's not the same scope as service's page is using.

At time the commit was added under Ferdi brand there supposed to be Wiki page that was explaining the feature under [this link](https://github.com/getferdi/ferdi/wiki/Using-user.css-and-user.js) but it's inaccessible now.

**Comment by Alphrag** [comment]
Hi @SelfRef, it is true that we haven't had the time to create a full wiki to try to get all the knowledge of the app into one place and might do so in the future. In the meantime, the repository of the [Ferdi wiki](https://github.com/getferdi/wiki/) is archived and thus you can have a look through it. In particular, you might be interested in the [file about `userfiles`](https://github.com/getferdi/wiki/blob/master/data/features/userfiles.md) to better understand the structure.
I unfortunately can't help you directly about that since I have never looked at its inner working.

**Comment by SelfRef** [comment]
Oh, so there is backup of the wiki. Thank you, that may help a lot 😉
