### ISSUE TITLE
unable to join teams meetings via URL

### ISSUE THREAD

**Issue by maurerr** [ferdium/ferdium-app#854]
### Your issue

Most likely I just don;t understand how ferdi(um) works but I just can't join a teams meeting via a url like ` https://teams.microsoft.com/l/meetup-join/19%3ameeting_blahblah blahAw%40thread.v2/0?context=%7b%22Tid%22%3a%2211111111-1111-40bf-bc48-1111111120%22%2c%22Oid%22%3a%2294177b10-7452-1111-1111-1111111%22%7d`

**Comment by Alphrag** [comment]
Hi, it is indeed normal that clicking on such a link outside of Ferdium (or in the app without asking to open in Ferdium by right-clicking) will open your browser and not redirect to Ferdium. In order to be able to do so, we would need to take control of deep links first, and then to find the appropriate service in which to open in. This is currently out of the scope of Ferdium and is unlikely to be implemented in the near future. What I would suggest if you want to use a link inside Ferdium is to copy it to your clipboard, then open the appropriate service in Ferdium and active the navigation bar (`View -> Toggle navigation bar` in the menu) so that you can paste the url you have copied. That way you can navigate to it in the container of the service to be connected.
