### ISSUE TITLE
Bug: I have to login again on other machines

### ISSUE THREAD

**Issue by ghost** [ferdium/ferdium-app#926]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

latest

### What Operating System are you using?

macOS

### Operating System Version

latest

### What arch are you using?

x64

### Expected Behavior

When I login on other machines, I shouldn't have to log back to synced services.

### Actual Behavior

I have to login again in synced services on other machines.

### Steps to reproduce

Yes.

**Comment by Gaboris** [comment]
Does this happen on systems you've already logged in and came back to later or you mean you freshly installed Ferdium, synced your services from a server and then started using that instance?

If so then that's expected behavior as transferring login or session data is not just a HUGE security concern(we do not transfer ANY sensitive data during sync for a reason), but most services actually have systems in place to prevent that as it's considered to be a phishing attempt.
