### ISSUE TITLE
Bug: uploading mac os screenshots

### ISSUE THREAD

**Issue by jnvillar** [ferdium/ferdium-app#937]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.5-nightly.3

### What Operating System are you using?

macOS

### Operating System Version

Ventura 13.0

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.2.5-nightly.1

### Expected Behavior

Every time I take a screenshot and drag it to a chat (whatsapp or telegram) the screenshot is correctly recognized as an image, uploaded and sent

### Actual Behavior

When I drag the screenshot a file is uploaded instead of a picture and the uploaded file can't be seen in the chat (the extension of the screenshot was lost I think)

If I drag the screenshot file from the desktop instead of the preview it still does not work

I have to manually add the extension to the file (I add `.png` to the end) and then it works as expected. This did not happen before the last update

### Steps to reproduce

1 take screenshot on mac (cmd + 3 or cmd + 4)
2 drag preview file to a wpp/telegram chat
3 a file is uploaded instead of an image/picture
4 send message
5 nobody in the chat can see the picture because it's not recognized as a one. (the extension info was lost)

### Screenshots

Telegram
<img width="418" alt="Screenshot 2023-02-07 at 11 44 29" src="https://user-images.githubusercontent.com/7551569/217276769-b66cb40a-8278-4fe8-a02f-24a2379d0467.png">

Whatsapp:
<img width="397" alt="Screenshot 2023-02-07 at 11 44 38" src="https://user-images.githubusercontent.com/7551569/217276804-175ced42-b5e2-454e-ad67-b36ef0c83421.png">

**Comment by jnvillar** [comment]
it happens in slack also

**Comment by jnvillar** [comment]
This is really annoying. 

Rollbacked to 6.2.5-nightly.1 and the bug is gone

**Comment by vraravam** [comment]
Thanks for bringing this up. I will take a look at it now and see what changed between the working version and now. Could I request you to try the latest nightly and confirm that this is still not working?

**Comment by vraravam** [comment]
I have done a quick scan of the codebase, and [this is the list of changes](https://github.com/ferdium/ferdium-app/compare/v6.2.5-nightly.1...v6.2.5-nightly.4) between the 6.2.5-nightly.1 and the latest code. Other than the electron upgrade from v22.x to v23.x, nothing has actually changed.

Have you upgraded your operating system recently? Or did you make changes to your OS configuration such that the screenshots are captured without an extension?

I also tried on my mac (but I am running Ventura 13.2beta on an m1 mac - and I am able to reproduce this. But, as I have always saved my screenshots with extensions, I never noticed this issue. btw, on macos at least, in the Finder app, if I remove the extension - even the OS/Preview app is unable to determine that the file is an image, and so it shows as a blank file icon.

Since we have literally done no changes other than bump up electron, I'm not sure what else we can do from our side.

Technically speaking, the OS sends the mime-type/content-type information when dragging and dropping files onto target applications, and if this is borked/changed from the OS-side, we will not be able to fix/tweak anything from our side to fix this ticket.

**Comment by jnvillar** [comment]
I did not change anything on my mac. I just upgraded ferdium (and rollbacking it makes the bug dissapear). My screenshots are saved with an extension but the extension is not shown on finder (I can see the extension in the terminal though so the file has an extension)

I will try with the latest nightly

**Comment by warrendt** [comment]
I have this problem as well with nightly 4

**Comment by jnvillar** [comment]
tried nightly 4 and I still have this problem

**Comment by jnvillar** [comment]
still broken on 6.2.5-nightly.5 (6.2.5-nightly.1 works fine)

**Comment by shepting** [comment]
I've found uploads of screenshots on macOS started failing for me last week on Github, and I believe it's related to the missing `.png` extension of the file. If I add it manually, it works. It could be related to this bug.

**Comment by warrendt** [comment]
I think you are onto something with the extensions, sending a screenshot through discord does the same thing, it doesn't add an extension to the image and gets to the other side, someone has to rename it or it won't open

**Comment by jnvillar** [comment]
> I've found uploads of screenshots on macOS started failing for me last week on Github, and I believe it's related to the missing `.png` extension of the file. If I add it manually, it works. It could be related to this bug.

mm but that would be strange because 6.2.5-nightly.1 works just fine

**Comment by jnvillar** [comment]
I could fix this by doing this

1 Open finder
2 Go to `Finder` (in the left top bar) -> `Settings` -> `Advanced` -> check `Show all filename extensions`

After this, `6.2.5-nightly.5` behaves just like `6.2.5-nightly.1` (I can upload screenshots just fine)

@shepting this also fixes your issue with github. I faced your issue, tried this and it worked. It seems to also fix the problem that I had in ferdium

**Comment by jsonperl** [comment]
> I could fix this by doing this
> 
> 1 Open finder 2 Go to `Finder` (in the left top bar) -> `Settings` -> `Advanced` -> check `Show all filename extensions`

I don't even know what Ferdium is but this fixed my annoying issue from macos screenshot -> github upload. Thank you!
