### ISSUE TITLE
Bug: Ferdium won't upgrade

### ISSUE THREAD

**Issue by desbest** [ferdium/ferdium-app#941]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 22H2

### What arch are you using?

x64

### Expected Behavior

Ferdium should upgrade after downloading the installer, with a window showing that it's doing so.

### Actual Behavior

Ferdium closes and doesn't upgrade. It was in the Task Manager for 30 minutes and still didn't upgrade. After 30 minutes I opened Ferdium and it was still on the same version.

### Steps to reproduce

Click the upgrade version once the "nightly" checkbox is ticked.

### Debug link

https://gitlab.com/-/snippets/2498318

### Screenshots

https://youtu.be/h9xfDQWQ0OY

**Comment by vraravam** [comment]
Looking through the ticket description, are you trying to upgrade from the stable to a nightly version?

I had tried this earlier when we released the first nightly after 6.2.4, and it was successful on my macos.

Can you please try manually installing one of the other nightlies, and then upgrading from within the app to the latest one? For eg, install v6.2.5-nightly.1, include nightly builds while checking for updates, and then see if it automatically updates to 6.2.5-nightly.4 (or whichever is the latest nightly at that point of time when you try this)

**Comment by desbest** [comment]
I've upgraded manually and it works now. 

However it's slow and it often crashes Windows Explorer (explorer.exe) so I'll just have to wait until the 6.2.5 (stable) version is finally released.

**Comment by vraravam** [comment]
The latest nightlies are based off of the latest stable version of electron (the core framework behind ferdium). Im sorry that you are facing performance and stability issues. I dont think we have had others report back along similar lines. We would be glad if you can confirm and continue to work with us using the nightlies and report back any issues that you may find. We will try to address those asap. TIA.

Can i close this ticket - since the original intent of it is now working?

**Comment by desbest** [comment]
You can close the ticket now.
